- .github/workflows/build.yml
Fixing github actions to release properly with tags
- Pushes latest and tagged version to docker
- Adds tag to release title
> Updating github actions yaml

- .github/workflows/build.yml
- .github/workflows/containers.yml
- .github/workflows/helm.yml
actions should only run on main branch
> run actions only on main

- pkg/direktiv/engine.go
> Logging jq no longer needs object output.

- pkg/direktiv/db-instance.go
- pkg/direktiv/engine.go
- pkg/direktiv/ingress.go
- pkg/direktiv/state-logic-switch.go
- pkg/direktiv/wli.go
- pkg/dlog/db/handler.go
- pkg/dlog/db/logger.go
> Improves workflow engine performance.

- pkg/direktiv/sync.go
> SyncSubscribeTo back

- pkg/direktiv/sync.go
Change SyncSubscribeTo function to use FlowSync pub/sub key.
> SyncSubscribeTo FlowSync

- pkg/direktiv/engine.go
> Fixes a panic that can happen in the instance cancelling logic.

- pkg/direktiv/db-instance.go
- pkg/direktiv/engine.go
- pkg/direktiv/errors.go
- pkg/direktiv/wli.go
- pkg/model/workflow.go
> 'singular' option to prevent workflows being run concurrently

- kubernetes/charts/direktiv/templates/api-cfg-cm.yaml
- scripts/knative/contour.yaml
- scripts/knative/install-knative.sh
- scripts/knative/knative-default.yaml
- scripts/knative/net-contour.yaml
- scripts/knative/serving-core.yaml
- scripts/knative/serving-crds.yaml
knative timeout updated to 2hrs
> timeout change knative, tls api helm update

- .github/workflows/containers.yml
- Makefile
- scripts/push/pushUI.sh
Git clones the UI and pushes the UI to localhost:5000/direktiv-ui.
> Added new push UI script

- .github/workflows/containers.yml
- Makefile
- scripts/push/pushUI.sh
- added the ability to self trigger build container components
- removed docker tag and pushes from the containers yml (controlled from the makefile step)
> Updated Workflow CI/CD

- .codeclimate.yml
Added metrics ignore to code climate
> Added ignoring metrics ent to code climate yml

- pkg/api/namespace.go
- added a content-type handler for events to handle aws properly.
> Added new content type check to header to support amazon events

- pkg/api/error.go
- pkg/api/util.go
Api errors refactored to be easily used by external package.
* Now correctly converting GRPC errors and codes,
* New exposed function to convert grpc errors
> Api error refactor

- pkg/api/server.go
- pkg/api/templates.go
Should achieve an 'A' rating on codeclimate
> Refactor pkg/api/templates.go

- Makefile
- scripts/knative/install-knative.sh
- scripts/knative/knative-autoscaler.yaml
- scripts/push/pushAll.sh
- scripts/resetAll.sh
Improvements for build scripts
> script changes

- cmd/sidecar/worker.go
added output directories for isolates. files in these directories will be automatically added as variables.
> added output dir for isolates

- pkg/direktiv/state-logic-consume-event.go
- pkg/direktiv/state-logic-eventsand.go
- pkg/direktiv/state-logic-eventsxor.go
- pkg/direktiv/state-logic.go
> Event consumers attempt to process jq.

- pkg/direktiv/state-logic-consume-event.go
- pkg/direktiv/state-logic-eventsand.go
- pkg/direktiv/state-logic-eventsxor.go
> Double-brace for jq in event context.

- pkg/direktiv/engine.go
- pkg/direktiv/flow.go
- pkg/direktiv/wli.go
> Workflow cancel overhaul (to make soft cancels catchable).

- pkg/direktiv/engine.go
> Prevents errors causing duplicate logs.

- cmd/sidecar/local-server.go
- cmd/sidecar/worker.go
> multiple var fixes

- pkg/model/workflow.go
Added json tags to workflow struct to false positive workflow unmarshal errors
> Model: Workflows, added json struct tags

- pkg/model/common-structures.go
- pkg/model/state-getter.go
- pkg/model/state-setter.go
Validates getter/setter state variable objects.
> Add validation for getter/setter variable fields in workflow yaml

- pkg/direktiv/state-logic-action.go
- pkg/direktiv/state-logic-foreach.go
- pkg/direktiv/state-logic-parallel.go
- pkg/model/common-structures.go
> Action input can now be provided as nested YAML.

- .github/workflows/build.yml
- .github/workflows/containers.yml
- .github/workflows/helm.yml
To prevent github actions running when not wanted.
> Changed from on create to on push

- pkg/direktiv/state-logic-eventsand.go
- pkg/model/state-events-and.go
> Fixes incorrect struct in model package.

- pkg/model/state-generate-event.go
> Generate event yaml tag fixed.

- pkg/direktiv/state-logic-action.go
> Now lone wildcards will be handled.

- pkg/api/routes.go
- pkg/api/server.go
Adds a health request route to the API server package.
> Add api/healthz route

- Makefile
- build/docker/all/app/main.go
- build/docker/api/Dockerfile
- build/docker/flow/Dockerfile
- build/docker/ui/Dockerfile
- kubernetes/charts/direktiv/kubescore.yaml
- kubernetes/charts/direktiv/templates/api-deployment.yaml
- kubernetes/charts/direktiv/templates/flow-deployment.yaml
- kubernetes/charts/direktiv/templates/ingress.yaml
- kubernetes/charts/direktiv/templates/nwp-api.yaml
- kubernetes/charts/direktiv/templates/nwp-denyall.yaml
- kubernetes/charts/direktiv/templates/nwp-grpc.yaml
- kubernetes/charts/direktiv/templates/nwp-sidecar-grpc.yaml
- kubernetes/charts/direktiv/templates/nwp-sidecar.yaml
- kubernetes/charts/direktiv/templates/nwp-support.yaml
- kubernetes/charts/direktiv/templates/nwp-ui.yaml
- kubernetes/charts/direktiv/templates/sidecar-cm.yaml
- kubernetes/charts/direktiv/templates/support-deployment.yaml
- kubernetes/charts/direktiv/templates/ui-deployment.yaml
- kubernetes/charts/direktiv/templates/ui-service.yaml
- kubernetes/charts/direktiv/values.yaml
- pkg/direktiv/grpc.go
- pkg/direktiv/health.go
- Added network policies and kubernetes probes
- Fixed issue with k3s with low cpu machines
- Persist db in docker-all image
> Networkpolicy & docker image fixes

- cmd/sidecar/local-server.go
- kubernetes/charts/direktiv/kubescore.yaml
- kubernetes/charts/direktiv/templates/nwp-sidecar.yaml
fixes network policy for knative sidecars
> fw fix for sidecar

- build/docker/all/Dockerfile
- build/docker/all/app/main.go
- build/docker/all/config-deployment.yaml
- build/docker/all/registry.yaml
- pkg/api/handlers.go
- added docker registry to docker all image
> better dev integration

- kubernetes/charts/direktiv/templates/ingress.yaml
- scripts/knative/knative-autoscaler.yaml
changes envoy timeout on contour-external
> envoy timeout

- cmd/sidecar/worker.go
- pkg/direktiv/state-logic-generate-event.go
- pkg/direktiv/state-logic-parallel.go
> Security tweaks.

- go.mod
- go.sum
- pkg/api/config.go
- pkg/api/instances.go
- pkg/api/namespace.go
- pkg/api/templates.go
- pkg/api/util.go
- pkg/api/workflow.go
Resolve code scanning alerts caused by the API package.
> Address code scanning alerts

- pkg/direktiv/engine.go
> engine fix

- pkg/direktiv/kubereq.go
Limit service names to 64 characters or less.
> Limit service names to 64 characters or less.

- .gitignore
- go.mod
- kubernetes/charts/knative/crds/serving-crds.yaml
- kubernetes/charts/knative/ed.script
- kubernetes/charts/knative/handleTemplates.sh
- kubernetes/charts/knative/templates/config-network.yaml
- kubernetes/charts/knative/templates/contour.yaml
- kubernetes/charts/knative/templates/net-contour.yaml
- kubernetes/charts/knative/templates/serving-core.yaml
- scripts/knative/serving-crds.yaml
> updated knative helm

- pkg/api/templates.go
- pkg/direktiv/config.go
Changed numbered nosecs to just nosec, and added to pkg/direktiv/config.go too
> Addressed a few false code-scanning alerts

- .github/workflows/build.yml
- Makefile
- build/docker/cli/Dockerfile
Signed-off-by: Trent Hilliam <trent.hilliam@vorteil.io>
> added windows and darwin binaries for the direkcli

- README.md
> Update readme to reflect new jq syntax

- .gitignore
- scripts/resetAll.sh
> gitignore update, helm install instead os script

- build/docker/all/app/main.go
- kubernetes/charts/knative/handleTemplates.sh
- kubernetes/charts/knative/templates/contour.yaml
reduced the replicas for contour
> changed contour replicas in docker-all

- kubernetes/charts/direktiv/templates/sidecar-cm.yaml
- kubernetes/charts/direktiv/values.yaml
> added optional net shaping pod config

- kubernetes/charts/direktiv/templates/sidecar-cm.yaml
> proxy typo

- .gitignore
- Makefile
- build/docker/init-pod/Dockerfile
- go.mod
- go.sum
> Pod approach fixes

- cmd/api/main.go
- cmd/init-pod/init.go
- cmd/init-pod/main.go
- cmd/init-pod/sidecar.go
- cmd/init-pod/vars.go
- go.mod
- pkg/api/handlers.go
- pkg/api/util.go
- pkg/api/workflow.go
- pkg/direktiv/db.go
- pkg/direktiv/engine.go
- pkg/direktiv/resolverDns.go
- pkg/direktiv/wli.go
> Suppress incorrect security notices.

- pkg/api/handlers.go
> Pod approach sec

- kubernetes/charts/direktiv/templates/flow-deployment.yaml
- kubernetes/charts/direktiv/values.yaml
- pkg/direktiv/config.go
- pkg/direktiv/engine.go
- pkg/direktiv/grpc-workflow.go
- pkg/direktiv/wfserver.go
- pkg/model/workflow.go
Checks on AddWorkflow and UpdateWorkflow if max scale is larger than configured amount. 
* Helm Updated
* Workflow model updated
* Workflow Engine check added (just in case)
> Max scale limit added to function scales

- pkg/direktiv/engine.go
- pkg/direktiv/state-logic-foreach.go
- pkg/direktiv/state-logic-parallel.go
Signed-off-by: trent <trent.hilliam@vorteil.io>
> Remove limits

- kubernetes/charts/knative/handleTemplates.sh
- kubernetes/charts/knative/templates/contour.yaml
> stop scraping contour

- .github/workflows/containers.yml
- kubernetes/charts/direktiv/values.yaml
- kubernetes/charts/knative/handleTemplates.sh
- kubernetes/charts/knative/templates/contour.yaml
> Init pod build

- kubernetes/charts/direktiv/templates/api-deployment.yaml
- kubernetes/charts/direktiv/templates/flow-deployment.yaml
- kubernetes/charts/direktiv/templates/sidecar-cm.yaml
- kubernetes/charts/direktiv/values.yaml
- pkg/direktiv/grpc_util.go
Adds configurable limits to grpc send and receive.
> Grpc limit

- kubernetes/charts/direktiv/templates/flow-secrets.yaml
- kubernetes/charts/direktiv/templates/isolate-secrets.yaml
> updated dns name for support db

- Makefile
> Changes protobuf logic to require manual invocation in the makefile.

- specification/isolated.md
> Adds a tiny bit of documentation for isolated functions.

- kubernetes/charts/direktiv/values.yaml
> modified values

- kubernetes/charts/direktiv/templates/functions-cm-config.yaml
- kubernetes/charts/knative/templates/config-autoscaler.yaml
- pkg/api/workflow.go
- pkg/direktiv/db.go
- pkg/direktiv/sync.go
- pkg/functions/config.go
- pkg/functions/kube.go
- pkg/functions/pod.go
- pkg/functions/server.go
Minor fixes in knative service management
> minor service fixes

- .github/workflows/helm.yml
- .gitignore
- Makefile
- build/docker/all/Dockerfile
- kubernetes/charts/direktiv/Chart.yaml
- kubernetes/charts/direktiv/values.yaml
> build fixes

- pkg/direktiv/grpc-instances.go
- pkg/direktiv/state-logic-consume-event.go
- pkg/direktiv/state-logic-eventsand.go
- pkg/direktiv/state-logic-eventsxor.go
- pkg/direktiv/state-logic-generate-event.go
- pkg/direktiv/state-logic.go
- pkg/direktiv/wli.go
> changed event consume/create logic

- kubernetes/charts/direktiv/Chart.yaml
> bump version

- pkg/flow/logs.go
- pkg/flow/server.go
- pkg/util/telemetry.go
> More information attached to logs.

- .github/workflows/containers.yml
Simple update for github action
> go-version updated on action

- Makefile
- kubernetes/charts/direktiv/values.yaml
- scripts/dev.yaml
Updated direktiv ui image tags from `direktiv-ui` to `ui`
> Updated direktiv ui image tags

- pkg/functions/kube.go
- pkg/functions/registries.go
> registry auth fix

- pkg/api/flow.go
- scripts/api/api.md
- scripts/api/swagger.json
Removed mention of body from await execute docs
> Removed mention of body from await execute docs

- pkg/flow/engine.go
- pkg/flow/state-action.go
- pkg/functions/server.go
> svc name changed

- pkg/flow/db-events.go
- pkg/flow/engine.go
- pkg/flow/events.go
> Fixes #264

- pkg/flow/state-action.go
- pkg/flow/state-foreach.go
- pkg/flow/state-generate-event.go
- pkg/flow/state-parallel.go
> Addresses Issue 268

- pkg/api/flow.go
- pkg/api/metrics.go
- pkg/api/server.go
- pkg/api/util.go
- pkg/flow/database.go
- pkg/flow/grpc-nodes.go
- pkg/flow/grpc-workflow.go
- pkg/flow/logs.go
- pkg/flow/metrics.go
- pkg/flow/scheduling.go
> Trace correlation

- pkg/api/flow.go
At the moment the API just accepts structured cloudevents. This change adds functionality required by cloudevents http protocol binding:
https://github.com/cloudevents/spec/blob/v1.0.1/http-protocol-binding.md
Additionally it "fixes" Azure's invalid cloudevents.
> cloudevent http binding

- pkg/api/flow.go
Added query parameter for recursive delete of a namespace
> Added ability to provide query param for recursive delete of a namespace

- pkg/flow/grpc-routing.go
- pkg/flow/grpc-workflow.go
Signed-off-by: trent <trent.hilliam@vorteil.io>
Fixed a bug with discarding workflow and ent.
> Fixed discard workflow

- scripts/README.md
> updated dev install readme

- scripts/install-eventing.sh
> install eventing script for testing

- pkg/flow/engine.go
- pkg/functions/kube.go
Fixed issue 316
Locally with flow tests
> issue 316 fix

- build/docker/all/debug.yaml
- build/docker/all/images.sh
- kubernetes/charts/direktiv/Chart.yaml
- kubernetes/charts/direktiv/README.md
> version tags

- .codeclimate.yml
Added new tests files to the ignore
> Added tests to code climate ignore

- Makefile
- pkg/api/client/global_services/global_services_client.go
- pkg/api/client/namespace_services/namespace_services_client.go
- pkg/api/client/variables/variables_client.go
- pkg/api/client/workflow_services/workflow_services_client.go
- pkg/api/flow.go
- pkg/api/functions.go
- scripts/api/api.md
- scripts/api/swagger.json
Fixed api docs creations and swagger comments
> API Docs Updated

- pkg/api/functions.go
- pkg/functions/registries.go
See issue description: https://github.com/direktiv/direktiv/issues/357
> fix for issue 357

- pkg/model/function-common.go
- pkg/model/state-getter.go
- pkg/model/state-setter.go
New regex validation added to model related to issue: https://github.com/direktiv/direktiv/issues/250
> New regex validation added to model

- kubernetes/charts/direktiv/templates/api/api-service.yaml
- kubernetes/charts/direktiv/templates/functions-timeout.yaml
- kubernetes/charts/direktiv/templates/functions/functions-cm-config.yaml
- kubernetes/charts/direktiv/templates/ingress-timeout.yaml
- kubernetes/charts/direktiv/templates/ui/ui-service.yaml
- kubernetes/charts/direktiv/values.yaml
- kubernetes/charts/knative/Chart.yaml
- kubernetes/charts/knative/crds/serving-crds.yaml
- kubernetes/charts/knative/ed.script
- kubernetes/charts/knative/handleTemplates.sh
- kubernetes/charts/knative/templates/config-autoscaler.yaml
- kubernetes/charts/knative/templates/config-defaults.yaml
- kubernetes/charts/knative/templates/config-deployment.yaml
- kubernetes/charts/knative/templates/config-features.yaml
- kubernetes/charts/knative/templates/config-network.yaml
- kubernetes/charts/knative/templates/serving-core.yaml
- pkg/functions/kube.go
The max timeout is now 2hrs for action requests. Added Knative v1.0.0
> knative 1.0 and timeout changes

- pkg/model/common-structures.go
- pkg/model/workflow.go
- specification/specification.md
Removed Schemas from top level workflow model / spec
Locally
> Model: Schemas from workflow spec.

- build/docker/all/app/main.go
- build/docker/all/config-deployment.yaml
- build/docker/all/images.sh
Updates docker all images to knative 1.0.0
> docker all update

- kubernetes/charts/direktiv/templates/flow/flow-cm-config.yaml
- pkg/flow/engine.go
- pkg/util/config.go
Warning added to action timeouts that are longer than allowed amount.
> Warning added to action timeouts that are longer than allowed amount.

- pkg/flow/grpc-workflow.go
Added more stream notifications
> added flow notification for workflow log to events

- pkg/api/functions.go
- pkg/api/routes.go
Added an api route for deleting workflow services.
closes: https://github.com/direktiv/direktiv/issues/393
> deleteWorkflowService api added

- pkg/flow/ent/migrate/schema.go
- pkg/flow/ent/runtime.go
- pkg/flow/ent/schema/namespace.go
> Adds a namespace character limit.

- pkg/flow/grpc-workflow.go
> Adds revision ID to response for multiple requests.

- pkg/metrics/metrics.go
> Fixes by-revision sankey data.

- build/docker/all/debug.yaml
- build/docker/all/images.sh
> Update version strings to v0.6.0

- scripts/dev.yaml
> changed default dev.yaml for initpod and sidecar changes in helm

- pkg/flow/memory.go
Fixes flow pod crashing by workflow referenced in this issue: https://github.com/direktiv/ui-december-2021/issues/219
> Fixed the flow pod crashing on certain event listeners

- pkg/api/functions.go
Updated the delete workflow service api to be more consistent with other workflow scoped api operations
Related: https://github.com/direktiv/direktiv/issues/393
> Update delete workflow service api

- build/docker/flow-dbinit/Dockerfile
Updated Alpine in intidb container
> update initdb alpine

- build/docker/all/images.sh
> all in one to 0.6.0

- pkg/flow/grpc-instances.go
Fixes workflow instances not returning routed instances.
> workflow instances api fixed

- pkg/flow/memory.go
- pkg/flow/scheduling.go
> Instances now fail if their revision is pulled out from underneath them.

- pkg/flow/routing.go
- pkg/flow/server.go
- pkg/flow/timers.go
Fixes an issue where crons can be duplicated
> fixed duplicate cron issue

- pkg/flow/logs.go
> Fixes a crash when a workflow is deleted with running instances.

- .gitignore
- scripts/README.md
- scripts/registry/registries.yaml
- scripts/registry/setup.sh
- scripts/registry/share/csr.conf
- scripts/registry/share/run.sh
- scripts/resetAll.sh
- scripts/resetk3s.sh
added scripts to setup a tls registry for development
> tls dev registry

- pkg/flow/state-getter.go
- pkg/model/state-getter.go
adds "system" scope to getter state with keys: uuid, epoch and instance for instance id.
> added system scope to state getter

- pkg/api/functions.go
- pkg/functions/kube.go
Better handling of testing private registries
> private registry fix

- pkg/api/flow.go
changes to event broadcast functions
> change functions for broadcast events

- pkg/functions/config.go
- pkg/functions/kube.go
- scripts/dev.yaml
This adds the option to add node affinity to knative pods
> pod node affinity

- go.mod
- go.sum
- pkg/flow/data.go
- pkg/jqer/jqer.go
Adds an additional scripting option with javascript. Equivalent to jq() but js() and javascript can be used.
> javascript handling

- pkg/secrets/server.go
Signed-off-by: Alan Murtagh <alan.murtagh@direktiv.io>
> Restricts secret names to a maximum of 32 characters.

- .github/workflows/containers.yml
- Makefile
removed init-pod from makefile
> removed init-pod from make

- go.sum
- pkg/flow/ent/edge.go
- pkg/flow/ent/instance_create.go
- pkg/flow/ent/instance_update.go
- pkg/flow/ent/migrate/schema.go
- pkg/flow/ent/schema/instance.go
- pkg/functions/ent/runtime/runtime.go
- pkg/functions/ent/services_query.go
- pkg/metrics/ent/metrics_query.go
- pkg/metrics/ent/runtime/runtime.go
- pkg/secrets/ent/namespacesecret_query.go
- pkg/secrets/ent/runtime/runtime.go
> Regex tweaks dirty

- cmd/exec/config.go
- cmd/exec/files.go
- cmd/exec/main.go
- cmd/exec/operations.go
Files also split for more readability.
> Exec auto config added and push command added

- cmd/flow/tests-instance-common.go
- cmd/flow/tests-instance-retries.go
- cmd/flow/tests-secrets.go
- cmd/flow/tests-vars.go
- pkg/api/flow.go
- pkg/api/metrics.go
- pkg/api/util.go
- pkg/flow/cancel.go
- pkg/flow/database.go
- pkg/flow/engine.go
- pkg/flow/grpc-flow.go
- pkg/flow/metrics.go
- pkg/flow/status.go
- pkg/util/instance.go
Signed-off-by: Alan Murtagh <alan.murtagh@direktiv.io>
> Minor refactor to avoid API server importing flow package.

- build/docker/api/Dockerfile.all
- build/docker/flow-dbinit/Dockerfile.all
- build/docker/flow/Dockerfile.all
- build/docker/functions/Dockerfile.all
- build/docker/secrets/Dockerfile.all
- build/docker/sidecar/Dockerfile.all
> Fixes #490

- pkg/flow/db-events.go
- pkg/flow/events.go
- pkg/flow/state-eventsand.go
- specification/workflow-yaml/events-and.md
> Fixes #493

- build/docker/api/Dockerfile.all
- build/docker/flow/Dockerfile.all
- build/docker/functions/Dockerfile.all
> Fixes #499

- pkg/flow/db-events.go
- pkg/flow/routing.go
> correlation removed. Fixes #503

- cmd/exec/config.go
- cmd/exec/main.go
Support added for windows and paths and some flag bug fixes 
> Exec windows support

- specification/workflow-yaml/consume-event.md
- specification/workflow-yaml/generate-event.md
> Fixed indentation errors in docs for events

- build/docker/all/debug.yaml
- build/docker/all/images.sh
- specification/workflow-yaml/setter.md
Makes docker all-in-one build more reliable
> All-in-one docker image update

- Makefile
> Alllow makefile to use .all docker files

- pkg/flow/syncer.go
> Mirror syncer logic now supports targz of variable-named directories.

- pkg/flow/state-setter.go
> Fixes #543.

- pkg/flow/syncer.go
> Mirror cron bugfix.

- pkg/flow/syncer.go
> Enforces mirror locks better, including for crons.

- pkg/flow/grpc-mirror.go
> Fixes an inconsistency between a streaming and a non-streaming API.

- pkg/flow/grpc-workflow.go
- pkg/flow/routing.go
- pkg/flow/syncer.go
> Fixes #557

- README.md
> Update to remove old Discord link and update Slack

- pkg/flow/syncer.go
> Fixes two minor bugs in the mirror syncing logic.

- pkg/flow/actions.go
- pkg/flow/cancel.go
- pkg/flow/locks.go
> Fixes #575

- cmd/exec/main.go
> Tweak to push auto path generation to work in more circumstances.

- Makefile
Adds makefile target: `clone-images` to clones remote images to local registry.
Targets: `clone-api clone-flow clone-secrets clone-sidecar clone-functions clone-flow-dbinit clone-ui` also added to clone images individually.
> Makefile target added to clone remote images to local registry

- Makefile
- build/docker/flow/Dockerfile
- scripts/install-dependencies.sh
Changes:
* Updated build image of flow Dockerfile to update glib used.
* Install Dependencies script added to install requirements for flow pod.
* `cluster` Makefile target will now automatically clone direktiv-charts if its missing.
* HELM_CONFIG Makefile variable will now read environment variable if set. Otherwise fallback to previous default value.
> Dockerfile Update and Install Dependencies script added

- Makefile
Adds some help text for `DOCKER_BASE` makefile option
> Makefile help text updated

- pkg/flow/events.go
> Minor refactor of event logic to better handle errors.

- pkg/model/common-structures.go
- pkg/model/state-events-and.go
- pkg/model/state-events-xor.go
> Closes #629

- pkg/flow/states/foreach.go
> Fixes #633.

- pkg/flow/states/action-helpers.go
- pkg/flow/states/action.go
- pkg/flow/states/foreach.go
- pkg/flow/states/helpers.go
- pkg/flow/states/parallel.go
- pkg/model/function-common.go
> Makes FunctionFiles fully jq-able.

- pkg/flow/syncer.go
> Fixes #611

- pkg/flow/temporary.go
- pkg/functions/kube.go
- pkg/functions/server.go
- pkg/model/function-global.go
- pkg/model/function-namespaced.go
- pkg/model/function-reusable.go
> Removes the ability to scale knative-workflow functions.

- pkg/flow/engine.go
- pkg/flow/status.go
Refer to issue #654 to understand the bug this is addressing and how to test it.
> Closes #654

- build/docker/all/installer/main.go
- cmd/exec/config.go
- cmd/exec/helloworld.yaml
- cmd/exec/main.go
- cmd/exec/operations.go
- scripts/api/api.md
Necessary changes to resolve https://github.com/direktiv/direktiv/issues/667
Additionally Fixes https://github.com/direktiv/direktiv/issues/664
https://github.com/direktiv/direktiv-ui/pull/324
https://github.com/direktiv/direktiv-react-hooks/pull/19
https://github.com/direktiv/direktiv/pull/668
https://github.com/direktiv/direktiv-charts/pull/25
> All-in-one and cli updated to authenticate with direktiv-token header

- cmd/exec/helloworld.yaml
Removes file pushed by accident.
> Removes helloworld.yaml

- pkg/flow/pagination.go
Fixes the bug in secrets pagination.
> Secrets pagination fix

- cmd/exec/main.go
- cmd/exec/types.go
> Fixes bug in exec command logs (wasn't updated to new pagination).

- cmd/exec/main.go
> Trim trailing slash from addr argument.

- pkg/flow/engine.go
> Fixes a false log when a catchable error wasn't handled.

- build/docker/flow/Dockerfile.all
> update ubuntu in flow

- build/docker/flow/Dockerfile.all
> Ubuntu update flow

- build/docker/flow/Dockerfile.all
- pkg/flow/temporary.go
eventAndState was broken because it was set to one event and state failed due to mismatch of number of events.
> eventAnd state was broken

- pkg/flow/syncer.go
> Automatic support for proxying in libgit2 logic.

- build/docker/all/Dockerfile
Simple upgrade of the Docker all-in-one image.
> Upgraded Ubuntu for all-in-one-image

- cmd/exec/main.go
> change error message to direktiv-sync

- Makefile
- build/ent/Dockerfile
- build/ent/run.sh
- build/protoc/Dockerfile
Protoc and ent is build with containers to ensure all devs using the same protoc and ent version
> protoc and ent build container

- pkg/functions/config.go
- pkg/functions/server.go
Watches configuration changes in function pod and reloads config on change.
> Watches configuration changes in function pod

- pkg/flow/syncer.go
Signed-off-by: Alan Murtagh <alan.murtagh@direktiv.io>
> Reverts one small change that broke mirrors.

- Makefile
- build/lint/Dockerfile
Adds a docker container for linting
> Add docker-based go linter

- pkg/api/flow.go
- pkg/flow/events.go
Some event.go eventFilter functions return internal server error, which should not do. Changed the target return error values. 
> change error code from 500 to 40X

- pkg/api/flow.go
> add term param to search

- cmd/exec/operations.go
- pkg/api/flow.go
> extend docs and solve tweak for send event with nn existing filter

- scripts/resetAll.sh
Fixed a problem with the resetAll script with knative using certificates
> fixed reset all with certificates

- pkg/flow/events.go
Event filters with broken scripts caused an go exit. This evaluates the script first and errors out if broken.
> fixed eventfilters with buggy filters

- scripts/reinstall-dev-stack.sh
- scripts/resetAll.sh
> Clean up code.

- pkg/flow/database/cache.go
- pkg/flow/grpc-workflow-variables.go
- pkg/flow/temporary.go
Fixes a couple of bugs from the cache push.
> Vars bugfix

- scripts/reinstall-dev-stack.sh
- scripts/resetAll.sh
This PR fixes minor bug in install scripts.
> BugFix sidecar image name in install scripts.

- scripts/install-eventing.sh
- scripts/reinstall-dev-stack.sh
Updated Knative eventing and serving. Charts updated to reflect the changes as well.
> Update Knative to 1.9.x

- pkg/flow/engine.go
- pkg/flow/grpc-logs.go
- pkg/flow/grpc-logs_test.go
- pkg/flow/mockdata/entlog_loop.json
- pkg/flow/mockdata/entlog_loopFunctionNested.json
- pkg/flow/states/action-helpers.go
- pkg/flow/states/action.go
- pkg/flow/states/instance.go
- pkg/flow/states/instance_test.go
- pkg/flow/temporary.go
> Fix missing loop-index tag when for-each invokes a sub-flow

- Makefile
> Ignore falsely flagged package from license-scanner

- .github/workflows/go-unittests.yml
> Mod test-runner to be able to work with embedded-db

- pkg/flow/grpc-mirror.go
- pkg/flow/server.go
- pkg/refactor/datastore/sql/file_annotations_test.go
- pkg/refactor/filestore/filestore.go
- pkg/refactor/filestore/path.go
- pkg/refactor/filestore/path_test.go
- pkg/refactor/filestore/psql/file_query_test.go
- pkg/refactor/filestore/psql/root_query.go
- pkg/refactor/filestore/psql/root_test.go
> Filesystem bug fixes

- .golangci.yaml
- Makefile
- pkg/flow/db-events.go
- pkg/flow/engine.go
- pkg/flow/events.go
- pkg/flow/grpc-revisions.go
- pkg/flow/grpc-routing.go
- pkg/flow/states/action-helpers.go
- pkg/flow/states/action.go
- pkg/flow/states/consumeEvent.go
- pkg/flow/states/delay.go
- pkg/flow/states/eventsAnd.go
- pkg/flow/states/eventsXor.go
- pkg/flow/states/foreach.go
- pkg/flow/states/instance_test.go
- pkg/flow/states/parallel.go
- pkg/flow/vars.go
- pkg/functions/kube-name.go
- pkg/functions/kube-status.go
- pkg/functions/kube.go
- pkg/jqer/jqer.go
- pkg/model/common-structures.go
- pkg/secrets/server.go
- pkg/util/grpc-util.go
> Enable more linters

- pkg/refactor/filestore/psql/file_query.go
- tests/jest/filesystem/workflow.test.js
> fix update workflow issue.

- .github/workflows/golint.yml
- .golangci.yaml
- Makefile
This PR make "make lint" runs fast.
> Enable "make lint" caching

- pkg/flow/grpc-flow.go
- pkg/flow/grpc-namespaces.go
- pkg/flow/grpc-refs.go
- pkg/flow/grpc-workflow.go
- pkg/flow/internallogger/logs.go
- pkg/flow/server.go
- pkg/refactor/datastore/sql/mirror.go
- pkg/refactor/mirror/sync.go
- pkg/refactor/mirror/sync_internal_test.go
- tests/jest/mirror/mirror.test.js
This implements direktiv vars.
> Implement direktiv variable.

- pkg/flow/internallogger/logs.go
- pkg/flow/server.go
- pkg/refactor/datastore/sql/file_annotations.go
- pkg/refactor/datastore/sql/file_annotations_test.go
- pkg/refactor/datastore/sql/mirror_test.go
- pkg/refactor/filestore/filestore.go
- pkg/refactor/filestore/psql/file_query.go
- pkg/refactor/mirror/mirror.go
- pkg/refactor/mirror/sync.go
- pkg/refactor/mirror/sync_test.go
- scripts/reinstall-dev-stack.sh
- tests/jest/filesystem/workflow.test.js
> Minor fixes

- pkg/flow/grpc-refs.go
- pkg/flow/server.go
- pkg/refactor/filestore/psql/file_query.go
- pkg/refactor/filestore/psql/revision_query.go
- pkg/refactor/filestore/psql/root_test.go
- pkg/refactor/filestore/revision.go
- pkg/refactor/filestore/revision_test.go
Fix file/dir renaming bug.
Fix tagging a revision bug.
> fix revision tagging.

- pkg/refactor/filestore/psql/filestore.go
- pkg/refactor/filestore/psql/revision_query.go
- pkg/refactor/filestore/psql/root_query.go
> fix queries.

- Makefile
- cmd/exec/cmd/config.go
- cmd/exec/cmd/workflows/workflows.go
- pkg/flow/grpc-workflow-variables.go
- tests/jest/variables/instvars.test.js
- tests/jest/variables/nsvars.test.js
- tests/jest/variables/wfvars.test.js
> Fixes workflow variable bug and cli variable upload

- Makefile
- pkg/flow/actionResults_test.go
- pkg/flow/grpc-internal.go
Signed-off-by: Alexander Ertli <alexander.ertli@direktiv.io>
> Fix actionlogs show dupplicated msgs

- tests/jest/cli/cli.test.js
Signed-off-by: Alexander Ertli <alexander.ertli@direktiv.io>
> Fix cli tests

- pkg/flow/database/entwrapper/database.go
- pkg/flow/grpc-mirror.go
- pkg/refactor/datastore/sql/file_annotations.go
- pkg/refactor/datastore/sql/mirror.go
- pkg/refactor/datastore/sql/mirror_test.go
- pkg/refactor/filestore/psql/file_query.go
- pkg/refactor/filestore/psql/filestore.go
- pkg/refactor/filestore/psql/revision_query.go
- pkg/refactor/filestore/psql/root_query.go
- pkg/refactor/mirror/mirror.go
- pkg/refactor/mirror/sync_test.go
- pkg/refactor/utils/mock.go
- tests/jest/cli/cli.test.js
This PR just fixes some table naming and clean up database queries. No behavior change introduced.
> Minor filesystem fixes and cleanups.

- pkg/flow/grpc-nodes.go
- pkg/flow/grpc-workflow.go
- pkg/refactor/core/file_annotations.go
- pkg/refactor/core/file_annotations_test.go
- pkg/refactor/core/file_user_attributes.go
- pkg/refactor/core/file_user_attributes_test.go
- pkg/refactor/datastore/datastore.go
- pkg/refactor/datastore/sql/datastore.go
- pkg/refactor/datastore/sql/file_annotations.go
- pkg/refactor/datastore/sql/file_annotations_test.go
- pkg/refactor/datastore/sql/mirror.go
- pkg/refactor/filestore/psql/file_query.go
- pkg/refactor/filestore/psql/filestore.go
- pkg/refactor/filestore/psql/revision_query.go
- pkg/refactor/filestore/psql/root_query.go
This PR adds more docs and tests of mirroring and file annotations.
> Add docs and tests.

- pkg/refactor/filestore/file.go
- pkg/refactor/filestore/filestore.go
- pkg/refactor/filestore/filestore_test.go
- pkg/refactor/filestore/path.go
- pkg/refactor/filestore/path_test.go
- pkg/refactor/filestore/psql/file_query.go
- pkg/refactor/filestore/psql/root_query.go
- pkg/refactor/filestore/revision.go
- pkg/refactor/filestore/revision_test.go
This PR adds more docs and tests.
> Add docs and tests to filestore package.

- pkg/flow/grpc-mirror.go
- pkg/refactor/mirror/mirror.go
- pkg/refactor/mirror/sync_test.go
This PR fixes mirroring process to have proper type.
> Fix mirroring process type.

- pkg/refactor/mirror/mirror.go
- pkg/refactor/mirror/sync.go
> Add more docs.

- pkg/flow/grpc-logs_test.go
- pkg/flow/internallogger/logs.go
Signed-off-by: Alexander Ertli <alexander.ertli@direktiv.io>
> \u0000 is not supported by PostgreSQL

- pkg/flow/events.go
- specification/workflow-yaml/events-xor.md
- tests/jest/events/events_filter.test.js
- tests/jest/events/send_events.test.js
- tests/jest/events/send_helper.js
- tests/jest/events/workflow_events.test.js
- tests/jest/events/workflow_events_and.test.js
- tests/jest/events/workflow_events_or.test.js
Added event testing and fixed SQL query to trigger workflows
> Event testing

- .github/workflows/build.yml
- .github/workflows/containers.yml
- .github/workflows/go-licenses.yml
- build/ent/Dockerfile
- build/protoc/Dockerfile
- pkg/flow/grpc-logs_test.go
This PR:
- fixes golang versioning in niesh places.
> fix golang versioning in niesh places.

- .github/dependabot.yml
- .github/workflows/build.yml
- .github/workflows/containers.yml
- .github/workflows/go-licenses.yml
- .github/workflows/go-unittests.yml
- .github/workflows/golint.yml
Add dependabot.yml and fix hard coded versions.
> Add dependabot.yml and fix hard coded versions.

- pkg/flow/grpc-workflow.go
Bugfixes:
- Invalid uuid when creating revision.
> Minor fix creating revision bug.

- pkg/flow/events.go
- tests/jest/events/events_filter.test.js
- tests/jest/events/send_events.test.js
- tests/jest/events/workflow_events.test.js
> fixed eventing filter bug

- kubernetes/install/knative/basic-proxy.yaml
- kubernetes/install/knative/basic.yaml
Fixes the example configuration for knative timeouts
> knative timeout fix

- cmd/flow-dbinit/main.go
> Fix flow dbinit main.go file.

- pkg/refactor/mirror/source.go
Allows self-signed certs in git pull
> insecure tls for git pull

- pkg/flow/database/entwrapper/database.go
- pkg/flow/ent/schema/events.go
- pkg/flow/ent/schema/instance.go
- pkg/flow/ent/schema/logmsg.go
- pkg/flow/ent/schema/varref.go
- pkg/refactor/utils/mock.go
> Fix filesystem tables schema

- cmd/flow-dbinit/main.go
Add fixes to flow db init script.
> Add fixes to flow db init script.

- tests/jest/secrets/secrets_crud_operations.test.js
> Add secrets e2e tests.

- pkg/refactor/datastore/datastoresql/logstore.go
- pkg/refactor/datastore/logstore_test.go
- pkg/refactor/logengine/logger.go
- pkg/refactor/logengine/logger_test.go
- pkg/refactor/logengine/logstore.go
- pkg/refactor/utils/mock.go
> Change loglevel to be an enum

- pkg/flow/server.go
- pkg/refactor/datastore/datastoresql/logstore.go
- pkg/refactor/datastore/logstore_test.go
- pkg/refactor/logengine/logger.go
- pkg/refactor/logengine/logger_test.go
- pkg/refactor/logengine/logstore.go
Prepare new logger for integration into the system
> Improve logging interface

- Makefile
> Rm ent-secrets

- pkg/flow/pubsub/pubsub.go
Removes dead-code from the pubsub pkg
> Rm dead code

- pkg/refactor/datastore/datastoresql/file_annotations.go
- pkg/refactor/datastore/datastoresql/mirror.go
- pkg/refactor/filestore/filestoresql/file_query.go
- pkg/refactor/filestore/filestoresql/filestore.go
- pkg/refactor/filestore/filestoresql/root_query.go
This PR fixes sql queries to be raw.
> Fix queries to be sql raw.

- Makefile
This PR adds clean-grpc make target.
> Add clean-grpc make target.

- pkg/functions/config.go
- pkg/functions/server.go
This PR remove functions config.go watcher.
> Remove functions config.go watcher.

- .github/workflows/golint.yml
- .golangci.yaml
- Makefile
- cmd/exec/cmd/instance.go
- pkg/flow/server.go
- pkg/refactor/logengine/logger.go
> Minor fixes.

- .golangci.yaml
- pkg/flow/broadcast.go
- pkg/flow/db-events.go
- pkg/flow/grpc-flow.go
- pkg/flow/grpc-instance-variables.go
- pkg/flow/grpc-instances.go
- pkg/flow/grpc-logs.go
- pkg/flow/grpc-namespace-annotations.go
- pkg/flow/grpc-workflow-variables.go
- pkg/flow/memory.go
- pkg/flow/routing.go
- pkg/flow/temporary.go
- pkg/flow/trace.go
- pkg/refactor/engine/child-info.go
- pkg/refactor/engine/descent-info.go
- pkg/refactor/engine/runtime-info.go
- pkg/refactor/engine/settings.go
- pkg/refactor/engine/telemetry-info.go
- pkg/refactor/instancestore/instance.go
> Minor issues

- pkg/refactor/instancestore/instance_data_query_test.go
- pkg/refactor/instancestore/instance_test.go
Fix unittests by disabling failing tests temporarily.
> Fix unittests by disabling failing tests temporarily.

- pkg/api/flow.go
- pkg/api/server.go
Minor fix api functions connection.
> Minor fix api functions connection.

- tests/jest/services/service_crud_and_run.test.js
> Add e2e tests to services.

- pkg/flow/events.go
> Add event filtering

- pkg/flow/events.go
adds full text search for event history
> 0.7.5/fulltext search

- pkg/flow/grpc-instance-variables.go
- pkg/flow/grpc/protocol.pb.go
- pkg/flow/grpc/protocol.proto
- pkg/flow/grpc/protocol_grpc.pb.go
Remove unused thread grpc methods.
> Remove unused thread grpc methods.

- pkg/refactor/engine/telemetry.go
This PR fixes/adds the callpath tag to the logs.
> Fix callpath-tag for smartlogs

- pkg/flow/errors.go
- pkg/refactor/core/namespaces.go
- pkg/refactor/datastore/datastoresql/namespaces.go
This PR fixes namespaces e2e tests.
> Fix tests.

- pkg/flow/bytedata/data2.go
- tests/jest/engine/cancel.test.js
- tests/jest/engine/catch.test.js
- tests/jest/engine/error-state.test.js
- tests/jest/engine/getter-setter.test.js
- tests/jest/engine/instance-data.test.js
- tests/jest/engine/noop.test.js
- tests/jest/engine/simple-chain.test.js
- tests/jest/engine/simple-events.test.js
- tests/jest/engine/simple-loop.test.js
- tests/jest/engine/simple-subflow.test.js
- tests/jest/filesystem/create_file.test.js
- tests/jest/filesystem/create_workflow_file.test.js
- tests/jest/mirror/mirror.test.js
- tests/jest/mirror/namespaces_git_mirror.test.js
- tests/jest/namespaces/lists.test.js
- tests/jest/namespaces/logs.test.js
- tests/jest/namespaces/namespace.test.js
- tests/jest/namespaces/namespaces.test.js
- tests/jest/namespaces/regex.test.js
- tests/jest/secrets/secrets_crud_operations.test.js
- tests/jest/secrets/secrets_read.test.js
- tests/jest/services/action_workflow_and_run.test.js
- tests/jest/services/service_crud_and_run.test.js
> Fix e2e test.

- Makefile
> Fix make file.

- pkg/flow/grpc-logs.go
- tests/engine/simple-subflow.test.js
- tests/package-lock.json
> Fix bugs in the logging logic introd. by refactor

- pkg/flow/events.go
- pkg/refactor/datastore/datastoresql/eventstore.go
- tests/events/send_events.test.js
this PR re adds the event filtering feature from 0.7.5 into the new event engine
> Read event filtering and Fix before date filter

- pkg/flow/grpc-flow.go
- pkg/refactor/datastore/datastoresql/logstore.go
- pkg/refactor/logengine/logstore.go
this PR readds the garbage collector using the data-store pattern
> Add garbage-collector for logs

- pkg/flow/db-events.go
- pkg/flow/eventing.go
- pkg/flow/events.go
- pkg/flow/trace.go
this PR adds basic tracing to the event processing. This is necessary to measure/validate the latency
> Add tracing to the eventing

- pkg/flow/server.go
- pkg/refactor/logengine/logger.go
- pkg/refactor/logengine/logger_test.go
- scripts/reinstall-dev-stack.sh
This PR introduces a toggles 1. for experimental features and 2. for developer mode
This will also disable the cluster package which is cause the sever to fail
> Add toggle to disable features

- pkg/flow/db-events.go
Fixes the code to be able to handle a empty lifespan value
> handle empty event lifespan value

- pkg/flow/events.go
This reverts commit dde9d27a5ae17941d02d31df4d6f2e96a01efb98.
and uncommenting a code block that was the one that incorrectly commented
> Revert "Rm dead code"

- pkg/refactor/datastore/file_annotations_test.go
- pkg/refactor/mirror/sync_test.go
> Fix mirror arguments order in tests

- pkg/api/functions.go
- pkg/flow/db-events.go
- pkg/flow/memory.go
- pkg/functions/kube-name.go
- pkg/functions/kube.go
- pkg/refactor/datastore/datastoresql/mirror.go
> Merge develop

- pkg/api/functions.go
Changed the path fro function logs to make it consistent
> added namespace to function logs

- pkg/api/functions.go
> Fix endpoints

- pkg/api/functions.go
> Fix WiP workflow-revision get request

- pkg/api/functions.go
- pkg/flow/isolate.go
This fixes a couple of workflow services bugs.
> Fix for a few workflow service bugs.

- pkg/api/functions.go
Reverts direktiv/direktiv#1062
> Revert "Fnroutefix"

- kubernetes/install/db/basic.yaml
- kubernetes/install/db/ha.yaml
- kubernetes/install/db/s3.yaml
- scripts/resetAll.sh
> fixed db config

- resources/direktiv.schema.json
> Add json-schema

- .github/workflows/review_deploy.yaml
> Change review-deyploments to other branch

- cmd/sidecar/worker.go
Fixes sidecar behaviour for non 200 response from a function container
> handling non 200 reponses from container

- cmd/exec/cmd/config/config-manager.go
- cmd/exec/cmd/config/project-conf-init.go
> chore: remove refs to deprecated io/ioutil

- Makefile
- pkg/refactor/service/docker_client.go
> Fix make env-stop target

- pkg/flow/temporary.go
- pkg/model/function-namespaced.go
- pkg/refactor/cmd/main.go
- pkg/refactor/core/service.go
- pkg/refactor/service/service_test.go
- pkg/refactor/spec/service.go
- tests/functions/files.test.js
- tests/services/new_service_crud_and_run.test.js
Remove service name from namespace services
> Remove service name from namespace services

- pkg/flow/temporary.go
> Fix the knative function logic not trying long enough.

- pkg/refactor/service/client.go
- pkg/refactor/service/docker_client.go
- pkg/refactor/service/helper.go
- pkg/refactor/service/knative_client.go
- pkg/refactor/service/manager.go
Minor fixes to services package
> Minor fixes to services package

- pkg/refactor/cmd/main.go
- pkg/refactor/core/app.go
- pkg/refactor/core/service.go
- pkg/refactor/service/helper.go
- pkg/refactor/spec/service.go
> Adds custom static environment variables for containers.

- Makefile
- pkg/refactor/cmd/main.go
- pkg/refactor/core/registry.go
- pkg/refactor/registry/registry.go
- pkg/refactor/registry/registry_mock.go
- tests/registry/multiple_namespaces.test.js
- tests/registry/registry_crud_and_run.test.js
> Fix registry

- Makefile
Apply version for testing docker image for E2E tests
> Change jest test image to fixed version

- docker-compose.yaml
- pkg/refactor/core/gateway.go
- pkg/refactor/gateway/consumer/consumer.go
- pkg/refactor/gateway/consumer/consumer_test.go
- pkg/refactor/gateway/endpoints/endpoints.go
- pkg/refactor/gateway/endpoints/endpoints_test.go
- pkg/refactor/gateway/endpoints/tree.go
- pkg/refactor/gateway/gateway.go
- pkg/refactor/gateway/gateway_test.go
- pkg/refactor/gateway/plugins/auth/basic-auth.go
- pkg/refactor/gateway/plugins/auth/basic-auth_test.go
- pkg/refactor/gateway/plugins/auth/key-auth.go
- pkg/refactor/gateway/plugins/auth/key-auth_test.go
- pkg/refactor/gateway/plugins/inbound/acl-plugin.go
- pkg/refactor/gateway/plugins/inbound/acl-plugin_test.go
- pkg/refactor/gateway/plugins/inbound/js-inbound.go
- pkg/refactor/gateway/plugins/inbound/request-convert.go
- pkg/refactor/gateway/plugins/inbound/request-convert_test.go
- pkg/refactor/gateway/plugins/outbound/js.go
- pkg/refactor/gateway/plugins/plugin.go
- pkg/refactor/gateway/plugins/target/instant-response.go
- pkg/refactor/gateway/plugins/target/target-ns-file.go
- pkg/refactor/gateway/plugins/target/target-ns-var.go
- pkg/refactor/gateway/plugins/target/target-workflow-var.go
- pkg/refactor/gateway/plugins/target/target-workflow.go
- tests/gateway/endpoints_crud.test.js
- tests/gateway/target_file.test.js
- tests/gateway/target_flow.test.js
- tests/gateway/target_ns_var.test.js
- tests/gateway/target_wf_var.test.js
Changed the gateway to use a `path` attribute instead of the file path within Direktiv
> changed gateway routes to use path

- pkg/refactor/service/knative_client.go
- tests/services/new_service_crud_and_run.test.js
> Fix service rebuild for k3s

- pkg/refactor/api/api.go
> Moves the middlewares.

- pkg/refactor/api/api.go
- pkg/refactor/api/middlewares.go
> Fix api routes.

- openapi/src/paths/gw_routes.yaml
- pkg/refactor/core/gateway.go
- pkg/refactor/gateway/endpoints/endpoints.go
- pkg/refactor/gateway/gateway.go
- pkg/refactor/gateway/plugins/target/target-ns-file.go
- pkg/refactor/gateway/plugins/target/target-ns-file_test.go
- pkg/refactor/gateway/plugins/target/target-ns-var.go
- pkg/refactor/gateway/plugins/target/target-ns-var_test.go
- pkg/refactor/gateway/plugins/target/target-workflow-var.go
- pkg/refactor/gateway/plugins/target/target-workflow-var_test.go
- pkg/refactor/gateway/plugins/target/target-workflow.go
- pkg/refactor/gateway/plugins/target/target-workflow_test.go
- tests/gateway/endpoints_crud.test.js
- tests/gateway/target_file.test.js
- tests/gateway/target_flow.test.js
- tests/gateway/target_ns_var.test.js
- tests/gateway/target_wf_var.test.js
- Added the server api key for the target plugins in gateway
- Updated openapi spec for the new `path` variable
- Added test for broken configurations for target plugins
- Added workflow error handling for target plugins
> Added api-key in gateway if set on server

- pkg/refactor/gateway/plugins/inbound/header_manipulation.go
- pkg/refactor/gateway/plugins/inbound/header_manipulation_test.go
> Add header plugin

- pkg/refactor/gateway/plugins/outbound/js_test.go
> Add one js-outbound test case

- pkg/refactor/gateway/endpoints/endpoints.go
- pkg/refactor/gateway/gateway.go
- tests/gateway/endpoints_crud.test.js
Fixed bug which caused a nil pointer exception with wrong end point configurations.
> Bugfix for endpoint config crash

- pkg/refactor/database/db_schema.sql
- pkg/refactor/datastore/datastoresql/datastore.go
- pkg/refactor/datastore/datastoresql/secrets.go
- pkg/refactor/datastore/datastoresql/secrets_test.go
- tests/secrets/secrets_read.test.js
> Fix secrets

- .github/workflows/golint.yml
- .golangci.yaml
- Makefile
- pkg/flow/grpc-nodes.go
- pkg/flow/pagination.go
- pkg/flow/pubsub/pubsub.go
- pkg/refactor/core/gateway.go
- pkg/refactor/core/service.go
- pkg/refactor/gateway/plugins/target/target-ns-file.go
- pkg/refactor/instancestore/instancestoresql/sql_builders.go
- pkg/refactor/logengine/logger.go
- pkg/refactor/mirror/apply.go
- pkg/refactor/service/docker_client.go
- pkg/refactor/service/helper.go
Upgrade linter version to v1.55
> Upgrade linter version

- openapi/src/paths/gw_routes.yaml
- pkg/refactor/core/gateway.go
- pkg/refactor/gateway/endpoints/endpoints.go
- pkg/refactor/gateway/endpoints/endpoints_test.go
- tests/gateway/endpoints_crud.test.js
- tests/gateway/target_file.test.js
- tests/gateway/target_flow.test.js
- tests/gateway/target_ns_var.test.js
- tests/gateway/target_wf_var.test.js
Cahnges API behaviour for target plugin
> target plugin epm,ty behaviour

- pkg/refactor/gateway/gateway.go
- pkg/util/telemetry.go
> Add initial tracing

- pkg/flow/server.go
Fix accidental removed eventing code.
> Fix accidental removed eventing code.

- pkg/flow/grpc-workflow.go
> Add consumer-type as valid file

- scripts/README.md
> Fix readme file

- pkg/refactor/service/helper.go
- pkg/refactor/service/knative_client.go
> Fix image pull secrets

- resources/direktiv.schema.json
> Fix direktiv workflow schema

- tests/gateway/target_flow.test.js
> Fix gateway-target 

- installer.sh
- scripts/install-monitoring.yaml
Automates the grafana setup steps 
& Fixes a issue in the otel configuration
> Fix grafana provisioning

- pkg/flow/grpc-instances.go
- pkg/refactor/gateway/plugins/target/target-workflow.go
- pkg/util/telemetry.go
This is a temporary solution. When we drop GRPC the problem will just go away
> Fix gateway-grpc Tracing

- tests/gateway/target_flow.test.js
fixes a path in a gateway test
> fixed gateway test

- pkg/refactor/database/db_schema.sql
- pkg/refactor/datastore/datastoresql/logstore.go
This PR drops the old way of indexing logs
> Optimization for log-queries

- resources/direktiv.schema.json
- Incorporating contribution (Commit: 898b036) from Pull Request #1178.
> Include file variable scope

- .github/workflows/k3s-e2e-tests.yml
> Add (readd) k3s pipeline tests

- .github/workflows/ui-storybook.yml
> Change wf trigger

- .github/workflows/api-e2e.yml
- .github/workflows/go-licenses.yml
- .github/workflows/go-lint.yml
- .github/workflows/go-unittests.yml
- .github/workflows/k3s-e2e-tests.yml
> Change triggers for wfs

- .github/workflows/ui-playwright.yml
> Add e2e test

- .github/workflows/ui-playwright.yml
> Fix playwright test

- .github/workflows/ui-playwright.yml
> Fix e2e test directory

- .github/workflows/ui-playwright.yml
> Change yaml to yaml

- .github/workflows/ui-playwright.yml
> Fix caching for docker-build again

- Makefile
> Fix makefile for monorepo

- Makefile
the installer.sh file was moved but the dependencies not updated
> Fix installer location

- .github/workflows/k3s-e2e-tests.yml
> Fix knative-cm location

- pkg/refactor/service/knative_client.go
> added error logging for the patch functionality

- scripts/build/docker/all/docker/Dockerfile
- scripts/build/docker/all/docker/debug.yaml
- scripts/build/docker/all/docker/installer/main.go
- specification/workflow-yaml/functions.md
- Updated spec for additional function params
- Update docker all in one image
> Spec Update & All-in-one

- tests/services/git_mirror_with_services.test.js
> [DIR-1118] Fix services e2e tests

- pkg/refactor/pubsub/sql/pubsub_core_pg.go
- pkg/refactor/pubsub/sql/pubsub_pg.go
> [DIR-1137] Refactor to core pubsub

- pkg/refactor/filestore/file_test.go
- pkg/refactor/filestore/filestoresql/file_query.go
- pkg/refactor/filestore/filestoresql/root_query.go
- pkg/refactor/filestore/revision.go
- pkg/refactor/filestore/root_test.go
> [DIR-1140] Fix field file.updated_at when updating a file content.

- .golangci.yaml
- cmd/cmd-exec/pkg/commands/commands_test.go
- cmd/cmd-exec/pkg/server/logging_test.go
- cmd/cmd-exec/pkg/server/server_test.go
- pkg/flow/grpc-nodes.go
- pkg/flow/grpc-workflow.go
- pkg/flow/server.go
- pkg/refactor/cmd/main.go
- pkg/refactor/pubsub/pubsub.go
- tests/events/workflow_events_and.test.js
- tests/events/workflow_events_or.test.js
- ui/frontend/main.go
- ui/frontend/server/config.go
- ui/frontend/server/error.go
- ui/frontend/server/route-manager.go
- ui/frontend/server/route.go
- ui/frontend/server/server.go
> [DIR-1148] move-configure-workflow-func-to-new-main

- pkg/flow/grpc-namespaces.go
- pkg/flow/grpc-nodes.go
- pkg/refactor/filestore/filestore.go
- pkg/refactor/filestore/filestoresql/root_query.go
- pkg/refactor/filestore/root_test.go
- tests/mirror/mirror.test.js
> [DIR-1150] refactor-remove-isempty-from-filestore

- pkg/flow/grpc-mirror.go
- pkg/flow/grpc-namespaces.go
- pkg/refactor/database/db_schema.sql
- pkg/refactor/datastore/runtime_variables_test.go
- pkg/refactor/filestore/file_test.go
- pkg/refactor/filestore/filestore.go
- pkg/refactor/filestore/filestoresql/file_query.go
- pkg/refactor/filestore/filestoresql/root_query.go
- pkg/refactor/filestore/root_test.go
- pkg/refactor/gateway/gateway_test.go
- pkg/refactor/mirror/mirror_test.go
- pkg/refactor/mirror/parser.go
- pkg/refactor/mirror/parser_test.go
> [DIR-1152] remove-root-dir-entries-from-filestore

- ui/Makefile
> Fixed colon missing in Makefile for frontend

- .github/workflows/api-e2e.yml
- .github/workflows/k3s-e2e-tests.yml
> [DIR-1215] Enable missing api e2e tests.

- .golangci.yaml
- openapi/src/objects.yaml
- openapi/src/openapi.yaml
- openapi/src/paths/filesystem.yaml
- pkg/refactor/api/api.go
- pkg/refactor/api/errors.go
- pkg/refactor/api/filesystem.go
- pkg/refactor/filestore/file.go
- tests/common/helpers.js
- tests/filesystem/read_directory_v2.test.js
> [DIR-1219] implement files tree read endpoint

- openapi/src/paths/filesystem.yaml
- pkg/refactor/api/filesystem.go
- tests/filesystem/read_directory_v2.test.js
> [DIR-1220] Add delete endpoint.

- pkg/flow/db-events.go
- pkg/refactor/database/db_schema.sql
- pkg/refactor/datastore/datastoresql/eventstore.go
- pkg/refactor/datastore/datastoresql/eventstore_test.go
- pkg/refactor/events/events.go
- tests/events/workflow_events.test.js
Makes event-listeners consider event-context on validation of the topic
> [DIR 1213] event topics are not including the event context

- openapi/src/paths/filesystem.yaml
- pkg/refactor/api/errors.go
- pkg/refactor/api/filesystem.go
- pkg/refactor/filestore/filestoresql/root_query.go
- tests/common/helpers.js
- tests/filesystem/create_file_v2.test.js
- tests/mirror/mirror.test.js
> [DIR-1225] add create files endpoints

- pkg/refactor/filestore/file.go
- pkg/refactor/filestore/filestoresql/filestore.go
- pkg/refactor/filestore/filestoresql/root_query.go
- tests/filesystem/create_file_v2.test.js
> [DIR-1226] fix-filesystem-size

- pkg/refactor/cmd/main.go
- pkg/refactor/filestore/filestore.go
- pkg/refactor/filestore/filestoresql/root_query.go
- pkg/refactor/gateway/gateway.go
> [DIR-1227] bugfix-filestore-listdirektivfileswithdata

- pkg/refactor/api/filesystem.go
- tests/common/helpers.js
- tests/filesystem/create_file_v2.test.js
- tests/filesystem/trailing_slash.test.js
- tests/filesystem/validation.test.js
- tests/filesystem/validation_v2.test.js
> [DIR-1231] add validation to create endpoints

- ui/e2e/settings/deleteNamespace.spec.ts
- ui/src/api/namespaces/query/get.ts
The list of namespaces is now sorted alphabetically everywhere.
> [DIR-1097] sort the namespaces in the drop down

- openapi/src/paths/filesystem.yaml
- pkg/refactor/api/filesystem.go
- tests/common/helpers.js
- tests/filesystem/create_file_v2.test.js
- tests/filesystem/trailing_slash.test.js
- tests/filesystem/update_file_path_v2.test.js
- tests/filesystem/update_file_v2.test.js
- tests/filesystem/validation_v2.test.js
> [DIR-1234] implement files tree update endpoint

- pkg/flow/grpc/protocol.proto
> [DIR-1236] cleanup grpc protocol file

- cmd/cmd-exec/pkg/commands/commands.go
- cmd/cmd-exec/pkg/commands/commands_test.go
- cmd/cmd-exec/pkg/server/server.go
- cmd/dinit/main.go
- cmd/direktiv/main.go
- tests/kubernetes/special-command.test.js
Adds an environment array to the special `cmd` for containers.
> [DIR-1190] Added environment variables to special command

- pkg/refactor/api/filesystem.go
- pkg/refactor/core/runtime_variables.go
- pkg/refactor/datastore/datastoresql/runtime_variables.go
> [DIR-1151] variables get flushed when a workflow is renamed via

- pkg/refactor/gateway/plugins/inbound/js-inbound.go
- pkg/refactor/gateway/plugins/inbound/js-inbound_test.go
- pkg/refactor/gateway/plugins/outbound/js.go
- pkg/refactor/gateway/plugins/outbound/js_test.go
- tests/gateway/js_inbound.test.js
- tests/gateway/js_outbound.test.js
Fixes header and query access in Javascript gateway plugin
> [DIR-1239] Fixed header and query access

- pkg/refactor/gateway/plugins/inbound/header_manipulation.go
- pkg/refactor/gateway/plugins/inbound/header_manipulation_test.go
- tests/gateway/http_header_plugin.test.js
The plugin will follow the common approach of name/value for the headers.
> [DIR-1221] Changed header manipulation plugin to name/value pairs

- tests/.eslintrc
- tests/common/config.js
- tests/common/filesystem.js
- tests/common/helpers.js
- tests/common/index.js
- tests/common/regex.js
- tests/common/structs.js
- tests/common/utils.js
- tests/filesystem/create_file.test.js
- tests/filesystem/create_file_v2.test.js
- tests/filesystem/create_workflow_file.test.js
- tests/filesystem/directory.test.js
- tests/filesystem/read_directory_v2.test.js
- tests/filesystem/root.test.js
- tests/filesystem/trailing_slash_v2.test.js
- tests/filesystem/update_file.test.js
- tests/filesystem/update_file_path_v2.test.js
- tests/filesystem/update_file_v2.test.js
- tests/filesystem/validation_v2.test.js
- tests/filesystem/workflow.test.js
- tests/package-lock.json
- tests/package.json
> [DIR-1244] Add eslint setup to e2e code

- .golangci.yaml
- pkg/refactor/api/api.go
- pkg/refactor/api/filesystem.go
- pkg/refactor/core/service.go
- pkg/refactor/filestore/file.go
- pkg/refactor/mirror/manager.go
- pkg/refactor/service/manager.go
> [DIR-1245] Maintain linter setting

- ui/e2e/errorPage.spec.ts
- ui/src/api/version/query/get.ts
- ui/src/api/version/schema.ts
- ui/src/pages/namespace/Layout.tsx
Switching to v2 version api. One e2e test was wating for a version request, I updated that to be more specific to make sure it's actually the v2 api that is requested
> [DIR-1214] switch to version v2 api

- pkg/refactor/service/knative_client.go
> [DIR-1200] services-are-not-deleted

- pkg/refactor/database/db_schema.sql
- specification/db_migration.md
> [DIR-1104] Create db migration document.

- pkg/refactor/gateway/plugins/inbound/js-inbound.go
- pkg/refactor/gateway/plugins/inbound/js-inbound_test.go
- pkg/refactor/gateway/plugins/plugin.go
- tests/gateway/js_inbound.test.js
Added consumer and url params to the Javascript plugin. Additional option to respond with an error code instead fo executing the plugin chain.
> [DIR-1145] Modified Javascript plugin to access consumer and URL parameters

- ui/Makefile
This handles the colon in the Makefile target `server-prod` correctly
> [DIR-1266] Fixed colon issue in server-prod target

- pkg/refactor/api/api.go
- pkg/refactor/api/filesystem.go
- pkg/refactor/cmd/main.go
- pkg/refactor/core/app.go
> [DIR-1264] Bugfix: publish pubsub events in filesystem apiv2

- pkg/refactor/api/api.go
- pkg/refactor/api/mirrors.go
- pkg/refactor/api/namespaces.go
- pkg/refactor/api/secrets.go
> [DIR-1291] prepare apiv2 skeleton

- pkg/refactor/api/api.go
- pkg/refactor/api/mirrors.go
- pkg/refactor/api/namespaces.go
- pkg/refactor/core/namespaces.go
- pkg/refactor/database/database.go
- pkg/refactor/datastore/datastoresql/mirror.go
- pkg/refactor/mirror/store.go
> [DIR-1291] Implement pesudo namespace api v2

- pkg/refactor/api/errors.go
- pkg/refactor/api/secrets.go
- pkg/refactor/core/runtime_variables.go
- pkg/refactor/core/secrets.go
- pkg/refactor/datastore/datastoresql/secrets.go
- tests/secrets2/basic_create.test.js
- tests/secrets2/basic_delete.test.js
- tests/secrets2/basic_update.test.js
- tests/variables2/basic_update.test.js
> [DIR-1296] Implement secrets v2 api

- pkg/flow/bytedata/data2.go
- pkg/flow/grpc-secrets.go
- pkg/flow/secrets.go
- pkg/refactor/api/errors.go
- pkg/refactor/api/secrets.go
- pkg/refactor/datastore/datastore.go
- pkg/refactor/datastore/datastoresql/datastore.go
- pkg/refactor/datastore/datastoresql/secrets.go
- pkg/refactor/datastore/datastoresql/secrets_test.go
- pkg/refactor/datastore/secrets.go
> [DIR-1297] refactor move secrets to datastore package

- pkg/flow/server.go
- pkg/refactor/mirror/apply.go
- pkg/refactor/mirror/callbacks.go
- pkg/refactor/mirror/manager.go
- pkg/refactor/mirror/mirror_test.go
- pkg/refactor/mirror/parser.go
- pkg/refactor/mirror/parser_test.go
> [DIR-1262] Implement mirror logs

- pkg/refactor/api/variables.go
- pkg/refactor/datastore/runtime_variables.go
- tests/secrets2/basic_create.test.js
- tests/secrets2/basic_crud.test.js
- tests/secrets2/basic_delete.test.js
- tests/secrets2/basic_update.test.js
- tests/secrets2/structure.test.js
- tests/variables2/basic_create.test.js
- tests/variables2/basic_crud.test.js
- tests/variables2/basic_delete.test.js
- tests/variables2/basic_update.test.js
- tests/variables2/structure.test.js
> [DIR-1303] Test listing variable and secrets

- pkg/refactor/api/errors.go
- pkg/refactor/api/namespaces.go
- pkg/refactor/datastore/mirrors.go
- tests/namespaces2/basic_create.test.js
- tests/namespaces2/basic_crud.test.draft.js
- tests/namespaces2/basic_delete.test.js
- tests/namespaces2/basic_update.test.draft.js
- tests/namespaces2/structure.test.draft.js
- tests/secrets2/basic_create.test.js
- tests/secrets2/basic_crud.test.js
- tests/secrets2/basic_delete.test.js
- tests/secrets2/basic_update.test.js
- tests/secrets2/structure.test.js
- tests/variables2/basic_create.test.js
- tests/variables2/basic_crud.test.js
- tests/variables2/basic_delete.test.js
- tests/variables2/basic_update.test.js
- tests/variables2/structure.test.js
> [DIR-1305] implement namesapces api v2

- pkg/refactor/api/filesystem.go
- pkg/refactor/api/namespaces.go
- pkg/refactor/pubsub/pubsub_pg.go
> Implement debounced publish pubsub

- openapi/src/openapi.yaml
- openapi/src/paths/filesystem.yaml
- pkg/refactor/api/api.go
- pkg/refactor/api/filesystem.go
- pkg/refactor/filestore/filestoresql/root_query.go
- tests/common/helpers.js
- tests/filesystem/create_file_v2.test.js
- tests/filesystem/read_directory_v2.test.js
- tests/filesystem/update_file_v2.test.js
- tests/filesystem/validation_v2.test.js
> [DIR-1302] improve v2 filesystem api semantics

- pkg/flow/engine.go
- pkg/flow/memory.go
- pkg/flow/metrics.go
- pkg/flow/scheduling.go
- pkg/flow/status.go
This PR attempts to fix the postgres deadlocks issue by more correctly handling cancelled contexts.
> [DIR-1317] Context fix for running instances

- .github/release.yml
- .github/workflows/charts.yml
- Dockerfile
- charts/direktiv/Chart.yaml
- charts/direktiv/templates/frontend/frontend-deployment.yaml
- pkg/flow/engine.go
- pkg/flow/grpc-mirror.go
- pkg/flow/locks.go
- pkg/flow/memory.go
- pkg/flow/metrics.go
- pkg/flow/scheduling.go
- pkg/flow/status.go
- pkg/refactor/datastore/datastoresql/logstore.go
- ui/Dockerfile.prod
Add release.yaml for auto-generating release notes
> [DIR-1281] Add release.yaml for auto-generating release notes

- README.md
Removed old broken link badges from README
> [DIR-1280] Removed README badges

- tests/.eslintrc
- tests/engine/cancel.test.js
- tests/engine/catch.test.js
- tests/engine/error-state.test.js
- tests/engine/getter-setter.test.js
- tests/engine/instance-data.test.js
- tests/engine/noop.test.js
- tests/engine/simple-chain.test.js
- tests/engine/simple-events.test.js
- tests/engine/simple-loop.test.js
- tests/engine/simple-subflow.test.js
> [DIR-1347] remove-old-filesystem-calls-from-engine-tests

- tests/functions/files.test.js
- tests/logparser/callpath.test.js
- tests/secrets/secrets_read.test.js
- tests/services/action_workflow_and_run.test.js
- tests/variables/instvars.test.js
- tests/variables/nsvars.test.js
- tests/variables/wfvars.test.js
> [DIR-1348] remove-old-filesystem-calls-from-variables-and-secrets-tests

- tests/common/helpers.js
- tests/engine/simple-subflow.test.js
- tests/events/workflow_events.test.js
- tests/filesystem/read_directory_v2.test.js
- tests/functions/files.test.js
- tests/gateway/endpoints_crud.test.js
- tests/gateway/http_header_plugin.test.js
- tests/gateway/js_inbound.test.js
- tests/gateway/js_outbound.test.js
- tests/gateway/target_file.test.js
- tests/gateway/target_flow.test.js
- tests/gateway/target_ns_var.test.js
- tests/gateway/target_wf_var.test.js
- tests/kubernetes/function-patch.test.js
- tests/kubernetes/generic-container.test.js
- tests/kubernetes/special-command.test.js
- tests/logparser/callpath.test.js
- tests/services/env_variables.test.js
- tests/services/new_service_crud_and_run.test.js
- tests/services/parse_multiple_workflow_services.test.js
- tests/services/rename_delete_service.test.js
- tests/services/update_service.test.js
> [DIR-1349] remove-old-filesystem-calls-from-gateway-tests

- .github/workflows/k3s-e2e-tests.yml
- tests/common/helpers.js
- tests/filesystem/read_directory_v2.test.js
- tests/filesystem/update_file_path_v2.test.js
- tests/gateway/endpoints_crud.test.js
- tests/services/rename_delete_service.test.js
- tests/services/update_service.test.js
> [DIR-1350] remove-all-legacy-filesystem-helper-functions-in-test-code

- pkg/flow/db-events.go
- pkg/flow/grpc-nodes.go
- pkg/flow/server.go
- pkg/refactor/api/filesystem.go
- pkg/refactor/pubsub/pubsub.go
> [DIR-1327] deleting-a-workflow-does-not-delete-a-event-listener

- openapi/src/openapi.yaml
- openapi/src/paths/paths.yaml
- openapi/src/paths/variables.yaml
> [DIR-1275] Add variables api docs

- .github/workflows/api-e2e.yml
- .github/workflows/ui-playwright.yml
- Makefile
- docker-compose.yaml
- ui/package.json
> [DIR-1359] playwrght simple implementation with make target

- docker-compose.yaml
- ui/Dockerfile
- ui/package.json
> [DIR-1360] Fix target make docker-e2e-playwright

- .github/workflows/k3s-e2e-tests.yml
- charts/direktiv/values.yaml
- tests/common/retry.js
- tests/logs/basic_namespace_logs.test.js
> [DIR-1357] Fix apiv2 logtest

- pkg/refactor/api/plattformlogs.go
> [DIR-1356] Cleanup logs v2

- pkg/jqer/jqer.go
- tests/engine/base64js.test.js
Adds `atob` and `btoa` to the js functionality in the engine.
> [DIR-1334] Added atob and btoa to js scripting

- charts/direktiv/Chart.yaml
> [DIR-1362] Update Direktiv version in charts

- .golangci.yaml
- cmd/exec/cmd/events/events.go
- cmd/exec/cmd/workflows/workflows.go
- pkg/api/util.go
- pkg/flow/grpc-logs.go
- tests/gateway/gitlab_auth.test.js
- tests/logs/basic_namespace_logs.test.js
- tests/services/new_service_crud_and_run.test.js
> [DIR-1366] 1366 routine backend cleanup

- pkg/refactor/datastore/datastoresql/eventstore.go
- pkg/refactor/datastore/datastoresql/eventstore_test.go
Fixes a issue with pagination for events
> [DIR-1379] event listeners error trailing junk after numeric literal at

- charts/direktiv/values.yaml
> [DIR-1382] Disable traced logging for now

- tests/engine/base64js.test.js
- tests/instances/blobs.test.js
- tests/instances/cancel.test.js
- tests/instances/wait-fail.test.js
- tests/logs/basic_namespace_logs.test.js
> [DIR-1389] Fix api tests

- pkg/flow/server.go
- pkg/refactor/mirror/callbacks.go
- pkg/refactor/mirror/manager.go
> [DIR-1389] Cleanup uber zap logger

- openapi/src/openapi.yaml
- openapi/src/paths/instances.yaml
- openapi/src/paths/paths.yaml
- openapi/src/paths/secrets.yaml
> Add secrets v2 openapi

- charts/direktiv/templates/flow/flow-secrets.yaml
> [DIR-1318] Keep encryption key in helm chart during update

- Makefile
Cross compile target was not building in new make target
> [DIR-1398] Fixed make target for UI build

- Makefile
> [DIR-1399] Fix UI build Makefile

- charts/direktiv/Chart.yaml
- charts/direktiv/values.yaml
> [DIR-1401] Update charts

- pkg/refactor/api/namespaces.go
- tests/namespaces/basic_create.test.js
- tests/namespaces/basic_crud.test.js
- tests/namespaces/basic_delete.test.js
- tests/namespaces/basic_update.test.js
- tests/namespaces/structure.test.js
> [DIR-1391] implement namespace api v2

- openapi/src/paths/paths.yaml
- openapi/src/paths/variables.yaml
> [DIR-1406] Fix variables api docs

- pkg/refactor/api/variables.go
- tests/variables2/list.js
> [DIR-1406] bug fix variables api v2

- pkg/refactor/datastore/mirrors.go
- tests/namespaces/basic_create.test.js
- tests/namespaces/basic_crud.test.js
- tests/namespaces/basic_update.test.js
- tests/namespaces/structure.test.js
> [DIR-1048] Fix mirroring object in namespace api v2

- pkg/flow/server.go
- pkg/refactor/api/api.go
- pkg/refactor/api/mirrors.go
- pkg/refactor/api/namespaces.go
- pkg/refactor/cmd/main.go
- pkg/refactor/core/app.go
- pkg/refactor/datastore/datastoresql/mirror.go
> [DIR-1414] implement mirroring api v2

- charts/direktiv/templates/flow/flow-deployment.yaml
- charts/direktiv/templates/frontend/frontend-deployment.yaml
> [DIR-1413] Fix invalid knative env vars in helm charts.

- docker-compose.yaml
- pkg/refactor/api/errors.go
- pkg/refactor/database/database.go
- pkg/refactor/database/db_schema.sql
- pkg/refactor/datastore/datastore.go
- pkg/refactor/datastore/datastoresql/runtime_variables.go
- tests/variables2/no_duplicated.test.js
> [DIR-1407] Fix creating duplicated variables bug.

- Makefile
- cmd/direktiv/flow.go
- pkg/api/entry.go
- pkg/flow/server.go
- pkg/refactor/api/api.go
- pkg/refactor/cmd/main.go
- pkg/refactor/core/circuit.go
- pkg/refactor/core/service.go
- pkg/refactor/pubsub/pubsub_pg.go
- pkg/refactor/service/manager.go
> [DIR-1419] implement graceful shutdown

- openapi/src/paths/paths.yaml
- openapi/src/paths/secrets.yaml
- pkg/refactor/datastore/datastoresql/runtime_variables.go
> [DIR-1428] fix sorting bug

- pkg/refactor/datastore/datastoresql/secrets.go
> [DIR-1428] Fix sorting secrets api v2

- pkg/refactor/api/secrets.go
- tests/secrets2/basic_create.test.js
- tests/secrets2/basic_crud.test.js
- tests/secrets2/basic_update.test.js
- tests/secrets2/structure.test.js
> [DIR-1428] Fix missed initialized field in secrets api v2

- openapi/src/paths/paths.yaml
- openapi/src/paths/variables.yaml
- pkg/refactor/api/variables.go
- tests/common/helpers.js
- tests/variables2/list.js
- tests/variables2/list.test.js
- tests/variables2/list_wih_filters.test.js
> [DIR-1436] add query string name filter to listing variables endpoint

- openapi/src/paths/namespaces.yaml
- openapi/src/paths/paths.yaml
- pkg/refactor/database/db_schema.sql
- pkg/refactor/datastore/datastoresql/mirror.go
- pkg/refactor/datastore/mirrors.go
- pkg/refactor/mirror/apply.go
- pkg/refactor/mirror/source.go
- tests/namespaces/basic_create.test.js
> [DIR-1437] add token field to v2 api namespace mirror

- openapi/src/paths/namespaces.yaml
- openapi/src/paths/paths.yaml
- pkg/refactor/api/namespaces.go
- pkg/refactor/datastore/datastoresql/mirror.go
- pkg/refactor/datastore/mirrors.go
- tests/namespaces/basic_update.test.js
- tests/variables2/list_wih_filters.test.js
- tests/variables2/no_duplicated.test.js
> [DIR-1438] make v2 api namespaces patchable

- pkg/jqer/jqer.go
This reverts commit 811d699fc107f2c7ffea2b7edef7e44e9b859c79.
> Revert "Should resolve DIR-1422. (#1420)"

- openapi/src/paths/paths.yaml
- openapi/src/paths/syncs.yaml
> [DIR-1437] Fix openapi docs

- pkg/refactor/mirror/apply.go
> [DIR-1441] Fix broken creation of depricated vriables in mirroring logic

- pkg/refactor/gateway/plugins/target/target-ns-file.go
- tests/gateway/target_file.test.js
Improves mimetype handling in file target plugin. First config value, then backend value and last attempt is guessing.
> [DIR-1446] Improve mimetype handling

- openapi/src/paths/namespaces.yaml
- openapi/src/paths/paths.yaml
- pkg/refactor/api/errors.go
- pkg/refactor/api/namespaces.go
- pkg/refactor/database/db_schema.sql
- pkg/refactor/datastore/datastore.go
- pkg/refactor/datastore/datastoresql/mirror.go
- pkg/refactor/datastore/mirror_test.go
- pkg/refactor/datastore/mirrors.go
- tests/namespaces/basic_create.test.js
- tests/namespaces/basic_update.test.js
> [DIR-1438] add namespace input field authType

- pkg/refactor/datastore/datastoresql/runtime_variables.go
> Normalize workflow path of variables

- pkg/flow/engine.go
> [DIR-1467] error messages are less helpful with unclear error codes

- charts/direktiv/Chart.lock
- charts/direktiv/templates/flow/flow-deployment.yaml
- pkg/refactor/mirror/source.go
- pkg/refactor/service/helper.go
> Apply Cycle4 to main

- pkg/refactor/api/notifications.go
Makes error message more consistent and fixes an e2e test as a result.
> Makes error message more consistent and fixes an e2e test as a result.

- .github/workflows/k3s-e2e-tests.yml
- openapi/src/openapi.yaml
- openapi/src/paths/metrics.yaml
- pkg/refactor/api/api.go
- pkg/refactor/api/metrics.go
- pkg/refactor/instancestore/instance.go
- pkg/refactor/instancestore/instance_test.go
- pkg/refactor/instancestore/instancestoresql/sql.go
- tests/metrics/workflow_metrics.test.js
Implements a v2 metrics API to replace the v1.
> [DIR-1472] Implements a v2 metrics API to replace the v1.

- ui/public/locales/en/translation.json
- ui/src/components/Logs/utils.ts
- ui/src/pages/namespace/Gateway/Routes/Detail/Logs/Entry.tsx
- ui/src/pages/namespace/Instances/Detail/Main/Logs/Entry.tsx
- ui/src/pages/namespace/Mirror/Activities/Detail/Logs/Entry.tsx
- ui/src/pages/namespace/Monitoring/Logs/Entry.tsx
⚠️ This is based on cycle4 for target cycle4.
Adds error messages to the logs if present:
* instances (can be tested with error workflow from the new workflow templates) 
* monitoring (namespace)
* routes
* mirror activities a.k.a syncs
Discussion:
* Formatting is a bit ugly, because sometimes msg ends with a dot, sometimes not, and "error" is not capitalized. This is a bit hard to read. But it's difficult to fix because the original data is not consistently formatted.
Todo:
> [DIR-1468] Render error messages in logs

- openapi/src/openapi.yaml
- openapi/src/paths/instances.yaml
- openapi/src/paths/paths.yaml
- pkg/api/flow.go
- tests/instances/blobs.test.js
- tests/instances/cancel.test.js
- tests/instances/wait-success.test.js
> [DIR-1504] Fix broken /namespaces/lint endpoint

- .github/workflows/backend_prebuild.yml
- .github/workflows/ui_prebuild.yml
> Minor Fixes: combine all ci jobs for backend, in a single workflow

- .github/workflows/backend-build.yml
- .github/workflows/backend-prebuild.yml
- .github/workflows/ui-prebuild.yml
> Minor Fix: Remove bananas from ci workflows

- .github/workflows/build.yml
> Minor Fix: e2e ci.

- .github/workflows/build.yml
- pkg/refactor/cmd/main.go
- pkg/refactor/core/gateway.go
- pkg/refactor/gateway/gateway.go
- pkg/refactor/gateway/gateway_test.go
> [DIR-1517] Remove unused code

- openapi/src/paths/events.yaml
- openapi/src/paths/paths.yaml
- pkg/refactor/api/events.go
> [DIR 1513] add missing resend a event API for v2

- openapi/src/paths/notifications.yaml
- pkg/refactor/api/notifications.go
- tests/part1/notifications/uninitialized_secrets.test.js
> [DIR-1521] Tweaks notifications api.

- pkg/refactor/database/db_schema.sql
> [DIR-1488] Removes the outdated metrics table from the database.

- .golangci.yaml
- pkg/refactor/api/api.go
- pkg/refactor/cmd/main.go
- pkg/refactor/core/app.go
- pkg/refactor/core/gateway2.go
- pkg/refactor/gateway2/gateway.go
- pkg/refactor/gateway2/plugins/basic_auth.go
- pkg/refactor/gateway2/plugins/plugins.go
> [DIR-1528] implement gateway2 mvp module

- pkg/refactor/api/namespaces.go
- tests/part2/namespaces/basic_create.test.js
> [DIR-1533] fix api/v2/namespace isSystemNamespace field

- pkg/flow/memory.go
- pkg/flow/scheduling.go
- pkg/refactor/instancestore/instancestoresql/instance_data_query.go
- tests/engine/sync.test.js
Fixes a bug in the synchronization logic of the engine and suppresses a number of handled errors (still viewable as debug logs).
> [DIR-1466] Fixes a bug in the synchronization logic of the engine.

- pkg/refactor/gateway2/gateway.go
- tests/gateway/endpoints_crud.test.js
- tests/gateway2/basic_auth.test.js
> [DIR-1541] implement basic auth e2e test

- .github/workflows/build.yml
- .golangci.yaml
- cmd/sidecar/local-server.go
- cmd/sidecar/worker.go
- make_tests.mk
- pkg/api/flow.go
- pkg/api/server.go
- pkg/flow/instance_messages.go
- pkg/refactor/api/events.go
- pkg/refactor/api/plattformlogs.go
- pkg/refactor/gateway/plugins/auth/slack-event.go
- pkg/util/telemetry.go
- tests/engine/sync.test.js
- tests/gateway2/basic.test.js
- tests/gateway2/basic_auth.test.js
- tests/part1/api/jx.test.js
> House Keeping

- tests/services/system_services.test.js
Adds e2e tests for current system services functionality.
> [DIR-1497] Adds e2e tests for current system services functionality.

- charts/direktiv/templates/flow/flow-deployment.yaml
- charts/direktiv/templates/frontend/frontend-deployment.yaml
- make_direktiv_ui.mk
- ui/conf/entrypoint.sh
- ui/conf/nginx.conf
Allows for additional envs in flow deployment charts.
> [DIR-1545] Updated charts for additional envs

- pkg/flow/db-events.go
> [DIR-1544] Fix rendering loop is returning to early

- pkg/flow/errors.go
- pkg/flow/jq.go
- pkg/flow/states/helpers.go
- pkg/flow/states/setter.go
- pkg/jqer/jqer.go
- pkg/refactor/api/instances.go
- pkg/refactor/api/jx.go
- tests/engine/simple-events.test.js
- tests/part1/api/jx.test.js
> [DIR-1553] Bugfixes

- make_direktiv_ui.mk
Fixes a typo in make target for cross-compiled UI
> [DIR-1554} UI make target fixed

- pkg/refactor/database/db_schema.sql
> [DIR-1556] Fix db migration line

- pkg/refactor/cmd/main.go
- pkg/refactor/core/gateway2.go
- pkg/refactor/gateway2/fetch_secret.go
- pkg/refactor/gateway2/fetch_secret_test.go
- pkg/refactor/gateway2/gateway.go
- tests/gateway2/fetch_secret.test.js
> [DIR-1557] gateway2: implement fetchSecret() magic function in consumer file

- charts/direktiv/Chart.yaml
Updates chart version to v0.8.6
> [DIR-1570] Update chart version

- charts/direktiv/values.yaml
- pkg/flow/engine.go
- pkg/flow/instance_messages.go
- pkg/flow/memory.go
- pkg/flow/status.go
- pkg/refactor/api/plattformlogs.go
- pkg/refactor/datastore/namespaces.go
- pkg/refactor/engine/telemetry.go
Fix issue with the fluent-bit tracking detection
> [DIR-1584] Fix regex issue & missing log prints

- pkg/flow/server.go
> [DIR-1589] Fix cleanups in initLegacyServer

- ui/src/api/logs/schema.ts
- ui/src/components/Logs/utils.ts
Update schema to allow state in instance logs to be null
> [DIR-1293] update schema to allow workflow state to be null

- .github/workflows/build.yml
- pkg/api/entry.go
> House Keeping: fix github actions to prevent run when building step is failed

- .github/workflows/build.yml
> House Keeping: prevent multiple concerent workflow for the same branch

- pkg/flow/grpc-instance-variables.go
- ui/src/App.css
> House Keeping: test ci run

- pkg/refactor/gateway2/context.go
- pkg/refactor/gateway2/plugins.go
- pkg/refactor/gateway2/plugins/target/request.go
- pkg/refactor/gateway2/plugins/target/target-ns-file.go
- pkg/refactor/gateway2/plugins/target/target-ns-var.go
- pkg/refactor/gateway2/plugins/target/target-workflow-var.go
- pkg/refactor/gateway2/plugins/target/target-workflow.go
- pkg/refactor/gateway2/router.go
- tests/events/workflow_events_or.test.js
- tests/gateway2/target_flow.test.js
- tests/gateway2/target_flow_var.test.js
- tests/gateway2/target_ns_file.test.js
- tests/gateway2/target_ns_var.test.js
- tests/services/system_services.test.js
> [DIR-1561] gateway2 migrate all target plugins from gateway1

- pkg/flow/engine.go
- pkg/flow/routing.go
- pkg/refactor/database/db_schema.sql
- pkg/refactor/instancestore/instance.go
- pkg/refactor/instancestore/instance_test.go
- pkg/refactor/instancestore/instancestoresql/sql.go
> [DIR-1597] Fix for the parallel crons issue.

- tests/part2/variables/workflow_link.test.js
> [DIR-1240] test variables links when workflow deleted or renamed

- tests/events/send_helper.js
> events tests fix

- pkg/refactor/api/sse_helper.go
- pkg/refactor/gateway/gateway.go
> Suppresses some spammy logs.

- .github/workflows/build.yml
- .golangci.yaml
- make_tests.mk
- pkg/refactor/core/service.go
- pkg/refactor/core/service_test.go
- pkg/refactor/service/service_test.go
- tests/services/action_workflow_and_run.test.js
> [DIR-1613] fix service id generation to respect RFC 1123 subdomain

- .github/workflows/build.yml
- docker-compose.yaml
- make_tests.mk
- tests/package.json
> House Keeping: clean jest run command

- pkg/refactor/api/events.go
- tests/events/send_events.test.js
- tests/events/send_helper.js
- tests/events/workflow_events.test.js
- tests/events/workflow_events_and.test.js
- tests/events/workflow_events_or.test.js
> [DIR-1511] Migrate tests to events v2

- charts/direktiv/Chart.yaml
> Chart Version Update

- pkg/refactor/api/events.go
- pkg/refactor/datastore/datastoresql/eventstore_history.go
- tests/events/events_v2.test.js
- tests/events/send_events.test.js
> [DIR-1616] Fix events-error handling

- tests/events/workflow_events_and.test.js
> [DIR-1617] Migrate test-case to new API endpoints

- pkg/tracing/context_builder.go
> [DIR-1633] Add namespace attr builder for logs

- openapi/src/openapi.yaml
> [DIR-1062] build open api docs

- pkg/database/db_schema.sql
> [DIR-1606] remove migration sql commands form the schema

- pkg/service/helper.go
This PR prepares the grpc removal from the sidecar
> [DIR-1641] Pass api-key to sidecar

- .github/workflows/build.yml
- Dockerfile
- ui/Dockerfile
> House Keeping: fix docker files for multi-platform images

- pkg/api/api.go
- pkg/api/filesystem.go
- pkg/api/namespaces.go
- pkg/cmd/main.go
- pkg/core/gateway.go
- pkg/core/service.go
- pkg/database/db_schema.sql
- pkg/filestore/filestore.go
- pkg/flow/server.go
- pkg/gateway/gateway.go
- pkg/gateway/plugins/inbound/request-convert.go
- pkg/gateway/plugins/target/target-workflow.go
- pkg/helpers/render.go
- pkg/pubsub/pubsub.go
- pkg/pubsub/pubsub_pg.go
- pkg/pubsub/sql/pubsub_core_pg.go
- pkg/service/manager.go
- tests/gateway/endpoints_crud.test.js
- tests/gateway/target_file.test.js
- tests/gateway/target_flow.test.js
- tests/part1/registry/multiple_namespaces.test.js
> House Keeping: fix todos

- pkg/pubsub/pubsub.go
- pkg/pubsub/pubsub_pg.go
- pkg/pubsub/sql/pubsub_core_pg.go
> House Keeping: remove global chanel in pubsub

- pkg/api/filesystem.go
- pkg/api/namespaces.go
- pkg/cmd/main.go
- pkg/flow/engine.go
- pkg/flow/instance_messages.go
- pkg/flow/server.go
- pkg/gateway/plugins/target/target-ns-file.go
- pkg/gateway/plugins/target/target-ns-var.go
- pkg/gateway/plugins/target/target-workflow-var.go
- pkg/gateway/plugins/target/target-workflow.go
- pkg/helpers/bus.go
- pkg/pubsub/pubsub.go
- pkg/pubsub/pubsub_pg.go
- pkg/pubsub/sql/pubsub_core_pg.go
> House Keeping: refactor pubsub

- cmd/sidecar/api_v2_clients.go
- cmd/sidecar/local-server.go
- cmd/sidecar/worker.go
- pkg/api/plattformlogs.go
- pkg/flow/temporary.go
- pkg/tracing/context_builder.go
removes the grpc usage in the sidecar
> [DIR-1669] remove grpc from the sidecar part3

- pkg/datastore/datastoresql/mirror.go
- tests/part1/registry/multiple_namespaces.test.js
- tests/part1/registry/registry_crud_and_run.test.js
Fixes the order of the mirror sync list
> [DIR-1661] Fix mirror log-list order

- tests/events/workflow_events_or.test.js
fixes a timing issue in the tests
> [DIR-1458] Fix test timing issue

- tests/kubernetes/generic-container.test.js
> [DIR-1701] Fix test-case

- pkg/core/service.go
- pkg/service/manager.go
> [DIR-1684] Fix server shutdown on bad service state

- pkg/api/instances.go
- pkg/api/sse_helper.go
- pkg/core/registry.go
- pkg/datastore/datastoresql/eventstore_history.go
- pkg/datastore/datastoresql/eventstore_topic.go
- pkg/datastore/datastoresql/mirror.go
- pkg/datastore/datastoresql/namespaces.go
- pkg/datastore/datastoresql/runtime_variables.go
- pkg/datastore/datastoresql/secrets.go
- pkg/datastore/mirror_test.go
- pkg/filestore/filestoresql/root_query.go
- pkg/registry/registry.go
- pkg/service/knative_client.go
- tests/part1/registry/multiple_namespaces.test.js
- tests/part1/registry/registry_crud_and_run.test.js
- tests/part1/secrets/basic_crud.test.js
- tests/part2/namespaces/basic_crud.test.js
- tests/part2/variables/basic_crud.test.js
- tests/part2/variables/list_wih_filters.test.js
- ui/e2e/mirror.spec.ts
I have made a few changes adding sort orders to existing queries. I have also added some TODOs to places where I think we might need sorting; or we probably should change the kind of sorting we're already doing. 
Please review these changes and push your own commits to this PR to resolve the TODOs I've added.
> [DIR-1714] Adds some sorting.

- tests/part1/registry/registry_crud_and_run.test.js
> Fix testing issue

- pkg/core/service.go
- pkg/service/knative_client.go
- pkg/service/manager.go
- tests/actions/action_workflow_bash_files.test.js
- tests/actions/action_workflow_bash_vars.test.js
- tests/actions/action_workflow_response.test.js
- tests/events/workflow_events_or.test.js
- tests/kubernetes/generic-container.test.js
- tests/part1/registry/multiple_namespaces.test.js
- tests/part1/registry/registry_crud_and_run.test.js
- tests/services/files.test.js
> House Keeping: fix error handling in services

- ui/e2e/instances/details/logs.spec.ts
Adds a test to ensure errors in the logs are rendered, including the error details.
> [DIR-1538] Add e2e test for error details in instance logs

- pkg/flow/temporary.go
- pkg/service/manager.go
> Add more log prints

- .github/workflows/build.yml
- pkg/gateway/router.go
- ui/src/api/logs/schema.ts
> [DIR-1756] Remove status from logs

- charts/direktiv/README.md
> Update helm docs

- cmd/sidecar/api_v2_clients.go
- cmd/sidecar/worker.go
> Fix error handling

- cmd/cmd-exec/main.go
- cmd/cmd-exec/pkg/commands/commands.go
- cmd/cmd-exec/pkg/commands/commands_test.go
- cmd/cmd-exec/pkg/server/logging.go
- cmd/cmd-exec/pkg/server/server.go
- cmd/dinit/main.go
> Add logging to cmd

- charts/direktiv/README.md
- charts/direktiv/templates/flow/flow-deployment.yaml
- charts/direktiv/values.yaml
- cmd/sidecar/local-server.go
- cmd/sidecar/main.go
- pkg/flow/server.go
> Fixing small issues

- make_cluster.mk
- scripts/README.md
> fixed some kind issues

- openapi/Makefile
> Change openAPI spec port

- pkg/instancestore/instance_test.go
> [DIR-1893] Re-enables instancestore test and fixes bugs within it.

- pkg/flow/engine.go
- pkg/flow/instance_messages.go
- pkg/flow/memory.go
- pkg/flow/scheduling.go
- pkg/flow/timeouts.go
> Fix logging bugs

- go.mod
- go.sum
- make_cluster.mk
- make_tests.mk
- pkg/core/gateway.go
- pkg/filestore/file.go
- pkg/gateway/gateway.go
- pkg/gateway/helper.go
- pkg/gateway/router.go
- pkg/helpers/render.go
- pkg/mirror/apply.go
- pkg/mirror/parser.go
- pkg/model/resources.go
- tests/gateway2/gateway_basic.test.js
- tests/gateway2/gateway_test.js
- ui/src/api/files/schema.ts
Handling of a basic OpenAPI file. Documentation will be changed when the initiative is completed.
> [DIR-1896] Add OpenAPI basic file

- .github/workflows/build.yml
- .golangci.yaml
- cmd/cli/filesystem.go
- cmd/cli/flow.go
- pkg/api/middlewares.go
- pkg/cmdserver/pkg/server/server.go
- pkg/filestore/filestoresql/root_query.go
- pkg/flow/instance_messages.go
- pkg/flow/memory.go
- pkg/flow/scheduling.go
- pkg/flow/states/action.go
- pkg/flow/states/foreach.go
- pkg/flow/states/parallel.go
- pkg/flow/states/validate.go
- pkg/model/common-structures.go
- pkg/model/start-event.go
- pkg/model/start-events-and.go
- pkg/model/start-events-xor.go
- pkg/model/state-generate-event.go
- pkg/model/state-parallel.go
- pkg/model/state-switch.go
- pkg/utils/encrypt.go
> [HK] fix linter issues and minor bugs

- pkg/database/database.go
- pkg/datastore/datastore.go
- pkg/datastore/datastoresql/datastore.go
- pkg/datastore/datastoresql/eventstore_history_test.go
- pkg/datastore/datastoresql/eventstore_listener_test.go
- pkg/datastore/datastoresql/eventstore_topic_test.go
- pkg/datastore/datastoresql/mirror.go
- pkg/datastore/datastoresql/secrets.go
- pkg/datastore/datastoresql/secrets_test.go
- pkg/datastore/mirror_test.go
- pkg/datastore/runtime_variables_test.go
- pkg/filestore/file_test.go
- pkg/filestore/filestore_test.go
- pkg/filestore/root_test.go
- pkg/flow/server.go
- pkg/instancestore/instance_data_query_test.go
- pkg/instancestore/instance_test.go
- pkg/instancestore/instancestoresql/instancestoresql_test.go
> [HK] fix datastore encryption key configuration

- pkg/flow/server.go
> [HK] fix datastore db typing

- ui/e2e/instances/list/index.spec.ts
We decided to skip this test for now, because it is very flaky = failing more often than not. I created a ticket for it to be fixed soon. => [Ticket](https://linear.app/direktiv/issue/DIR-1918)
> Fix e2e test

- openapi/src/paths/instances.yaml
- openapi/src/paths/paths.yaml
- pkg/api/instances.go
- tests/instances/wait-success.test.js
This PR adds a new flag `output` to the instance API to alter the response from raw to a instance summary.
> [DIR-1928] Add output flag to instance API

- Dockerfile
- make_tests.mk
- ui/package.json
> Lock pnpm version

- make_tests.mk
- openapi/src/paths/gateway.yaml
- pkg/gateway/gateway.go
> [DIR-1956] Added server variable to openapi docs

- pkg/api/filesystem.go
> [DIR-1973] fix runtime variables update on file path change

- ui/src/design/RapiDoc/index.tsx
- ui/src/design/RapiDoc/styles/RapiDoc.css
I updated font for Rapidoc component
> Changed font Rapidoc

- tests/part2/namespaces/basic_create.test.js
> [DIR-1995] fix bug: namespace 'api', 'v2' or 'namespace' could break the backend logic

- pkg/api/namespaces.go
> [DIR-1996] endpoint namespaces is public

- ui/src/pages/namespace/Explorer/Page/poc/BlockEditor/index.tsx
- ui/src/pages/namespace/Explorer/Page/poc/PageCompiler/Block/utils/BlockWrapper.tsx
- ui/src/pages/namespace/Explorer/Page/poc/PageCompiler/context/__tests__/utils.test.ts
- ui/src/pages/namespace/Explorer/Page/poc/PageCompiler/context/pageCompilerContext.tsx
- ui/src/pages/namespace/Explorer/Page/poc/PageCompiler/context/utils.ts
- ui/src/pages/namespace/Explorer/Page/poc/PageCompiler/index.tsx
- ui/src/pages/namespace/Explorer/Page/poc/PageCompiler/primitives/Variable/index.tsx
- ui/src/pages/namespace/Explorer/Page/poc/PageEditor.tsx
- ui/src/pages/namespace/Explorer/Page/poc/schema/__tests__/examples/complex.ts
- ui/src/pages/namespace/Explorer/Page/poc/schema/__tests__/examples/simple.ts
> [DIR-2034] Add unit tests for page editing methods

- pkg/gateway/router.go
- tests/gateway2/basic.test.js
- tests/gateway2/timeout.test.js
This is actually a bug not a feature.
> [TDI-76] Add error message for method not supported to gateway

- pkg/cmdserver/pkg/commands/commands.go
Returns native JSON if the command in the speical command is returning JSON string.
> [TDI-88] JSON response in command

- .github/workflows/build.yml
> fix github actions
