- pkg/direktiv/isolates-cache.go
- pkg/direktiv/secrets.go
- pkg/direktiv/state-logic-action.go
- pkg/direktiv/state-logic-foreach.go
- pkg/direktiv/state-logic-parallel.go
Makes GetSecretsWithData return data, Fixes a panic following that to do with invalid authentication when pointing to an external registry.
Connected to marketplace.gcr.io with service account and a 60 minute access token
> GetSecretsWithData now returns the data for registries, fixed following panic with invalid authentication

- scripts/resetAll.sh
IP addresses are not getting cleaned up when using the `resetAll` script. This will cause k8s to run out of addresses if the `resetAll` script is executed enough times.
> direktiv resetAll script updated to remove old ip addresses

- cmd/api/main.go
- kubernetes/charts/direktiv/templates/api-deployment.yaml
- kubernetes/charts/direktiv/templates/secrets.yaml
- kubernetes/charts/direktiv/values.yaml
Support added to Authorization apiKey for the api binary. This auth step is optional and can enabled by passing the DIREKTIV_API_KEY environment. Helm has been setup to pass this env as a secret also.
> Authorization apiKey added to api and helm chart

- pkg/api/error.go
Exposeed GenericErrorCode so it can used in other packages
> Api: Expose GenericErrorCode so it can used in other packages

- pkg/api/namespace.go
- pkg/direktiv/grpc.go
- logs the type and source for the cloud event
- unmarshals the cloud event on the api handler to handle validation
> Added a new log to namespace for broadcasting events.

- pkg/direktiv/engine.go
When checking for catchable errors, treat '\*' as '\.\*' to match any catchable error.
> Catch error wildcard

- go.mod
- go.sum
- kubernetes/charts/direktiv/templates/api-blocklistnamespaces-cm.yaml
- kubernetes/charts/direktiv/templates/api-cfg-cm.yaml
- kubernetes/charts/direktiv/templates/api-deployment.yaml
- pkg/api/config.go
- pkg/api/namespace.go
- pkg/api/server.go
Add a new configmap for the API server and added a new library to handle badwords. 
- First filter swearing
- Restrict creation of namespaces where the name exactly matches a reserved word (for example: 'api').
> Added namespace filtering to prevent badwords and reserved words

- kubernetes/charts/direktiv/templates/sidecar-cm.yaml
Use the value of `.Values.flow.maxScale` to set the `autoscaling.knative.dev/maxScale` annotation in the sidecar configmap.
> Add maxScale to sidecar-cm template, set by .Values.flow.maxScale.

- pkg/direktiv/wli.go
… status
When calling a error state in an instance, the instance status will be set to error. However the workflow should be able to continue, and should not cause a internal error. This changes checking instance status to checking instance endtime when reporting results.
Tested with a few different workflows to make sure that the result is correct.
> Logic fix to stop incorrectly causing internal error when instance status is error

- kubernetes/charts/direktiv/templates/api-deployment.yaml
- kubernetes/charts/direktiv/templates/api-service.yaml
- kubernetes/charts/direktiv/templates/ingress.yaml
- kubernetes/charts/direktiv/templates/ui-deployment.yaml
- kubernetes/charts/direktiv/templates/ui-service.yaml
- pkg/api/server.go
Setting the `flow.certificate` field in a helm config file will result in all relevant internal components using that certificate for TLS connection within the cluster.
> Internal tls

- pkg/api/flow.go
- pkg/api/functions.go
- pkg/api/util.go
- scripts/api/api.md
- scripts/api/swagger.json
- scripts/dev.yaml
Go Swagger Docs added in comments.
Running `$ make api-docs; make host=EXT_IP01 api-swagger` will create docs and run a local swagger client to test them.
> Go-swagger docs added for api's

- pkg/flow/state-action.go
Checks for duplicate var file names (checking `as` and `key`) and reports an error before sending the request to the workflow.
> Fixes #180

- Makefile
- pkg/api/flow.go
- pkg/api/functions.go
- scripts/api/api.md
- scripts/api/swagger.json
- Doc comments updated so that generated markdown can work with jekyll
- Makefile api-docs target updated to fix generated markdown
- Small corrections to api docs
> go-swagger docs updated to work with jekyll

- pkg/flow/ent/schema/ref.go
- pkg/flow/ent/schema/regex.go
The workflow 'ref' regex followed our standard naming regex, but in this context that was too restrictive. Refs couldn't begin with a digit, which caused issues because they were being auto-generated from their revision UUIDs (which can begin with numbers). Besides, wanting to tag something as `0.5.0` is perfectly reasonable, and should be made possible. 
> Changes workflow ref regex to be more permissive.

- .github/workflows/helm.yml
Changed the Github Actions workflow that published Helm charts to support versioning (previous would simply overwrite the existing chart).
If this PR is accepted, please note that the `GCP_CREDENTIALS` repository secret must be set, to hold the base64-encoded contents of a Google Cloud Platform service account JSON key. `GCP_BUCKET` must equal the name of the bucket as it appears on Google Cloud Platform (ie. `my-bucket`, and NOT `my-bucket/charts`).
> Rewrite helm github actions workflow to support versioning

- pkg/flow/engine.go
- pkg/util/grpc-util.go
Maintain consistency between start type even triggered instances and execute instances to list the same.
> Added a sanitize function to trim the prefix slash from instance name

- pkg/flow/engine.go
- pkg/flow/grpc-flow.go
- pkg/flow/server.go
The bug only happened when retries were scheduled more than 5s into the future, which wasn't part of our test scripts until now.
> Fixes #326

- kubernetes/charts/direktiv/templates/flow/flow-secrets.yaml
- kubernetes/charts/direktiv/values.yaml
The key for secrets was generated by default. Which makes all secrets invalid on redeploy. Set the default to some dummy value prevents this from happening. 
If key was set it was not base64 encoded also and did not work at all.
> default encryption key set

- pkg/flow/ent/pagination.go
- pkg/flow/ent/schema/inode.go
- pkg/flow/grpc-nodes.go
Added the Name, Created, and Updated as supported fields to order by when getting directory nodes.
Locally
> New Ordering Fields Added

- .github/workflows/helm.yml
The AppVersion is being used for the default tags of each image in the Direktiv helm charts. Currently this is being set to the tag, minus the leading 'v' character.
This change tells the github action to not remove the v from the AppVersion value.
> Set helm AppVersion to full tag (without cutting leading 'v').

- kubernetes/charts/direktiv/README.md
- kubernetes/charts/direktiv/templates/functions/functions-deployment.yaml
- kubernetes/charts/direktiv/templates/ui/ui-deployment.yaml
- kubernetes/charts/direktiv/values.yaml
References to replicaCount replaced with replicas in helm charts
> References to replicaCount replaced with replicas

- pkg/flow/grpc-internal.go
- pkg/flow/logs.go
If you log a special character from a workflow to the side car and that log message has a special Sprintf character, the interal logger will attempt the resolve this special character with no additional.
The internal ActionLog has been updated to use a new function `logToInstanceRaw` which prints the string as is.
> logging fix for action lodging string interpolation

- pkg/flow/engine.go
- pkg/flow/status.go
Signed-off-by: Trent <trent.hilliam@vorteil.io>
Pubsub notifications for when an instance status changes for the instances list. Side effect means computation goes up but  UX gets better.
> Added sub notifications on instances for status changes

- pkg/flow/grpc-instances.go
Added filter.type=WORKFLOW to instances filtering
Example query:
filter.field=AS&filter.type=WORKFLOW&filter.val={$WORKFLOW_NODE}
> AS WORKFLOW query filter added to instance filter

- pkg/flow/metrics.go
Prometheus counters currently do not have a field for workflow revisions. Because of this I've removed the revision ref from the driektiv_workflow prometheus key. This is a temporary fix and should be added back in when revision ref has been split and is stored in new counter key. I'll make an issue to track this
> revisions trimmed from prometheus metrics temporarily

- pkg/functions/kube.go
- pkg/functions/pod.go
If you execute a workflow with a ref=REVISION_UUID and the workflow service hasn't spun up yet it will try to create a Kubernetes service with a label `"direktiv.io/path=WF_NAME:REVISION_UUID`. The `:` character is illegal in kube labels so this service will fail and the instance will also fail. 
This pr trims the `REVISION_UUID` from the path in the services. I've had a look at the flow and functions code and don't think it will cause any problems anywhere else. I've also done some testing locally and it all seems to work. 
It's a small change, but I'm making this a pr incase there some side-effect you know of that I'm forgetting about.
I also did think about sanitizing the label instead of just trimming it, but I feel like this just adds confusion. Example scenario:
1. Create a revision …
> Revision suffix removed from workflow service paths

- pkg/flow/grpc-instances.go
Adds new options for filtering on the instance status list. 
You can filter on either `AS` or `STATUS`. 
`AS` refers to the `as` field, which is the string used to invoke/call the workflow. `AS` can have filter types `WORKFLOW` or `CONTAINS`. The latter is a simple string match, while the former attempts to match the prefix only so that the specific tag/ref/revision used (if any) is irrelevant. 
`STATUS` refers to the `status` field. `STATUS` can have filter types `MATCHES` or `CONTAINS`. Both are basic string matches, though the former must be an exact match. 
This issue is slightly related to #400.
> New filtering options for instances list.

- pkg/flow/grpc-routing.go
prevents the routing service to add 0% routing to the table
> avoid adding 0 values to routing table

- pkg/api/server.go
Azure requires an additional header in the options response *WebHook-Allowed-Rate*. 
Closes #434
> fixed azure option issue. Closes #434

- pkg/flow/grpc-workflow.go
Signed-off-by: Alan Murtagh <alan.murtagh@direktiv.io>
> Fixes a crash that can happen when calling the DiscardHead api.

- cmd/sidecar/worker.go
This is a fix to align the max payload size between API and internal communication.
> modify sidecar max size to API value

- pkg/flow/locks.go
- pkg/flow/syncer.go
Lock functionality does not return the connection to the connection pool if acquiring the lock fails after getting the connection from the pool.
> Fixed lock connection handling Closes #547

- cmd/exec/main.go
- cmd/exec/operations.go
- pkg/flow/grpc-nodes.go
* CreateDirectory crash fix.
* cli Push now makes parent dirs.
* cli Push now toggles parent mirror to r/w if necessary.
* Fixes #566
> Cli improvements

- cmd/sidecar/worker.go
- pkg/util/grpc-util.go
> Sidecar can accept empty variables of type tar and tar.gz, Increased max GRPC size

- pkg/api/flow.go
- pkg/api/util.go
The tag and retag API operations now support reading `tag` from both query and body. Support for reading from body was added because the `tag` query was causing the API to be falsely flagged by some ad blockers.
Note: The query value of `tag` will be given priority if `tag` is in both query and body.
Tested locally.
> API: tag can now be read from query or body in tag operations

- cmd/exec/main.go
- cmd/exec/operations.go
Fixes: https://github.com/direktiv/direktiv/issues/604 - Flag `--no-push` added to exec command
Fixes: https://github.com/direktiv/direktiv/issues/596 - Automatically setting nodes to writable on push removed and instead cli will error and report to user that node is readOnly. `set readonly` and `set writable` commands added to change permissions of remote nodes.
Additional Bug Fix: Checking the readOnly status of a node in a namespace that doesnt exist was causing a infinite loop. To prevent this the namespace is "pinged" in the root command pre-run now.
> CLI Enhancements & Fixes

- pkg/api/util.go
Fixes [612](https://github.com/direktiv/direktiv/issues/612)
Changes sse heartbeat frequency from every 10 -> 5 seconds. Although this doubles the number of events the UI will recieve, these messages have no data attached to them, thus barely increasing the traffic overall. However if this bug is left as is, whenever a connection is terminated and re-established, all data needs to be sent again essientally doubling the traffic.
> Increase SSE Heartbeat Frequency

- pkg/flow/data.go
Removes unused import that was causing flow builds to fail.
> unused ent import removed from flow

- pkg/api/flow.go
extend replayEvent http handler to allow slashes for types
per insomnia
Broadcast an event which his ID field include slashes and replay it 
> allow retrigger events which id field includes slashes

- pkg/api/flow.go
- scripts/api/api.md
- scripts/api/swagger.json
jens comments for this PR: 
- Search and overwrite should be args 
/namespaces/{ns}/secrets/{secret:.*[^/]$}?op=search&term=whatever
The functions sharing the same path and and 'op' parameter defines what it does.
op=set (default if it is not set)
op=search&term=whattosearch
op=update
My changes: 
combined both handler search and overwrite. Still not good solution in my opinion, because it's mixing patch and get...
By default, know it's an overwrite when adding query param op like ?op=search it will use the search function
**Operating system:** OSX/Windows 10/Ubuntu …
> combine overwrite and search secrets handler

- pkg/api/functions.go
fixed name generation for namespace pod lookup
> fixed namespace pod search

- .gitignore
- scripts/README.md
- scripts/resetAll.sh
K8s feature-gates 'TTLAfterFinished'  flag was removed [see this](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates-removed/).
This PR removes 'TTLAfterFinished' usage in the k3s installation instruction.
> 738 install k3s instructions in readme is broken

- scripts/resetAll.sh
I left an exit 1 in the resetAll.sh script and Knative does not need annotations anymore.
> fixed a script bug

- pkg/flow/actions.go
- pkg/flow/bytedata/data.go
- pkg/flow/engine.go
- pkg/flow/events.go
- pkg/flow/functions.go
- pkg/flow/grpc-inode-annotations.go
- pkg/flow/grpc-instance-annotations.go
- pkg/flow/grpc-instance-variables.go
- pkg/flow/grpc-instances.go
- pkg/flow/grpc-logs.go
- pkg/flow/grpc-mirror.go
- pkg/flow/grpc-namespace-annotations.go
- pkg/flow/grpc-namespace-variables.go
- pkg/flow/grpc-namespaces.go
- pkg/flow/grpc-nodes.go
- pkg/flow/grpc-refs.go
- pkg/flow/grpc-revisions.go
- pkg/flow/grpc-routing.go
- pkg/flow/grpc-secrets.go
- pkg/flow/grpc-workflow-annotations.go
- pkg/flow/grpc-workflow-variables.go
- pkg/flow/grpc-workflow.go
- pkg/flow/jq.go
- pkg/flow/pubsub.go
- pkg/flow/routing.go
- pkg/flow/trace.go
In order to decouple the architecture as a frist step we could move most of the methods from data.go file into a own pkg. This step would be also necessary to decouple our logging system from the server/flow pkg.
Signed-off-by: Alexander Ertli <alexander.ertli@direktiv.io>
> Refactor atob into own package

- pkg/flow/cancel.go
- pkg/flow/states/action-helpers.go
- pkg/flow/states/action.go
- pkg/flow/states/foreach.go
- pkg/flow/states/instance.go
- pkg/flow/states/instance_test.go
- pkg/flow/states/logic.go
- pkg/flow/states/parallel.go
- pkg/flow/temporary.go
This tweaks the foreach state's logic to push through at most three child threads at a time. This should help prevent engine overload for large arrays. 
The number 3 is not currently configurable. Should it be? If not, do we want to leave it at 3?
> Runs foreach logic in batches to help prevent engine overload.

- pkg/flow/cancel.go
- pkg/flow/engine.go
- pkg/flow/events.go
- pkg/flow/grpc-instances.go
- pkg/flow/grpc-namespaces.go
- pkg/flow/pubsub/pubsub.go
- pkg/flow/routing.go
- pkg/flow/server.go
- pkg/flow/syncer.go
- pkg/flow/timeouts.go
- pkg/flow/timers.go
Moving the `pubsub.go` into a own package. 
This step is needed to refactor the logging into a own package.
And would help us to write unit tests for pub sub functionality.
> Move pub-sub code into a separate package

- .github/workflows/build.yml
- .github/workflows/containers.yml
- .github/workflows/go-licenses.yml
- .github/workflows/go-unittests.yml
- .github/workflows/golint.yml
- .golangci.yaml
This PR workaround golangci-lint [panic: cannot convert *t0 (M) to PM) issue](https://github.com/golangci/golangci-lint/issues/3711)
> workaround golangci-lint issue.

- pkg/flow/engine.go
- pkg/flow/server.go
- pkg/flow/temporary.go
- pkg/refactor/logengine/logger.go
this PR prepares the new logger to replace the old internal logger.
- change the type of the tags from map[string]interface{} to map[string]string
- Add the mapping from the user-facing tag keys to the new db-column names from the PR https://github.com/direktiv/direktiv/pull/937
- fix one line in engine.go so that it will work with the new logger
> prepare betterlogger to replace the old solution

- tests/logparser/callpath.test.js
this PR adds e2e test-cases to test 
- if the source instance log-view contain the child instance logs
- if the instance logs contains all important attributes
- if the callpath attribute is structured like it should
- if the tracing attribute is set
> Add testcases for the logs-structure

- pkg/flow/server.go
the GORM logger is not outputted as json. At least the it should be wrapped in a JSON-style logger so that we don't break other the parsing for other components.
> Wrap gorm logger in a json-style logger

- .github/workflows/go-unittests.yml
- Makefile
this PR removes the -p1 argument since its no longer needed.
It was used when we used the embedded postgres db inside the unit-tests
> Rm -p1 argument

- scripts/reinstall-dev-stack.sh
Removes the need that we always have to remember to update the branch-name used in the current helm-chart branch.
Instead we should just apply our newest patches to the develop branch in the helm-chart repo so that i will be used by our reinstall-script
> Pin reinstall script to helm-charts develop branch

- pkg/refactor/filestore/path.go
This reverts commit 1cb2e49
creating a namespace was not possible this PR fixes the issue by reverting the change to the regex
See: https://github.com/direktiv/direktiv/actions/runs/5471876848/job/14815699997 for the origin of the issue
> Fix sanitize-path breaks the backend

- pkg/flow/server.go
Gorm-logger was not using the debug-flag this bloated the console log in some cases
> Make gormlogger use debug env

- .github/workflows/go-unittests.yml
This PR changes the unit-test pipeline so that it excludes tests testing private methods from the pipeline.
> Fix pipeline should not run private tests

- pkg/flow/grpc-namespaces.go
- pkg/refactor/cmd/main.go
- pkg/refactor/pubsub/pubsub_sql.go
- tests/gateway/endpoints_crud.test.js
The gateway route structures are getting setup on git mirror. This did not work with local-only namespaces. This adds a pubsub for namespace create which triggers the gateway setup.
> Fix non-mirror gateway routes

- pkg/flow/grpc-workflow.go
- ui/e2e/errorPage.spec.ts
- ui/e2e/explorer/workflow/codeEditor.spec.ts
- ui/e2e/notificationmenu/index.spec.ts
- ui/public/locales/en/translation.json
- ui/src/pages/namespace/Explorer/Workflow/Edit/CodeEditor.tsx
- ui/src/pages/namespace/Explorer/Workflow/Edit/WorkflowEditor.tsx
- ui/src/util/router/ErrorPage.tsx
Show the last time the file was changed in the code editor again. This also fixes a backend issue where the response of the file update, did return the old updated at
> [DIR-1141] reenable the updated at in the code editor

- ui/src/pages/namespace/Instances/Detail/InstanceDetail.tsx
- ui/src/pages/namespace/Instances/Detail/Main/Diagram/index.tsx
- ui/src/pages/namespace/Instances/Detail/Main/Diagram/utils.ts
The diagram of a workflow instance shows the finish state, even if the workflow is still running.
- Create this workflow that runs for 20 seconds and finishes afterwards
```yaml
direktiv_api: workflow/v1
description: A simple 'delay' state that waits for 5 seconds
states:
- id: delay
type: delay
duration: PT20S
``` 
- run the workflow
- the diagram displays the workflow as completed, even if it is still pending
Fixed in this PR: the diagram does not indicate that the workflow has completed
> [DIR-1025] Instance shows finished in UI although not completed

- ui/e2e/explorer/consumer/index.spec.ts
- ui/e2e/explorer/consumer/utils.ts
- ui/src/pages/namespace/Explorer/Consumer/ConsumerEditor/Form/index.tsx
- ui/src/pages/namespace/Explorer/Consumer/ConsumerEditor/index.tsx
- ui/src/pages/namespace/Explorer/Service/ServiceEditor/index.tsx
- introducing e2e test to the consumer editor. 
- this also fixes an issue where the keys of the yaml were sorted differently after saving (as we already addressed in the services)
- I also removed an unnecessary `compareYamlStructure ` in the service editor. I introduced the compareYamlStructure function to detect changes even if the keys were sorted differently. But since you already solved the root cause and the keys are now always sorted the same way, this function call is not needed any more (and your test are still passing). [I suggested this change here](https://github.com/direktiv/direktiv/pull/1204/files#r1467458062) but lost track of it.
> [DIR-1194] test consumer editor

- pkg/refactor/gateway/plugins/target/target-workflow.go
- tests/gateway/target_flow.test.js
Default content-type was set to `text` instead of `json` for the flow target plugin. The default response type is json for Direktiv and this PR configures the content type to json if not set in configuration.
> [DIR-1243] Set default content type for flow target plugin

- .github/workflows/go-unittests.yml
- pkg/refactor/gateway/plugins/plugin.go
Gateway plugins load on startup during `init`. This causes logging in the Direktiv sidecar in functions. This will guard the login registration for the sidecar and will prevent logs from being in the sidecar logs.
> [DIR-1135] Load plugins in flow only

- cmd/cmd-exec/pkg/commands/commands.go
- cmd/cmd-exec/pkg/server/server.go
The error attribute for the special `/usr/share/direktiv/direktiv-cmd` stopped the subsequent executions of commands but did not mark the action as failed. This patch fixes this it.
> [DIR-1207] Changed stop behaviour for "error" attribute for special command

- ui/e2e/instances/list/index.spec.ts
- ui/e2e/services/details.spec.ts
- ui/e2e/services/list.spec.ts
- ui/e2e/services/utils.ts
- ui/e2e/utils/files.ts
Our tests for the services were written based on their behavior in the Docker driver setup.
Some aspects behave differently in the k8s setup with Docker Desktop.
This updates the tests to expect that behavior, in addition to some changes related to our update to the v2 filesystem API.
I replaced the redis image used in the service tests with a http image as recommended by the backend team. 
The redis image has some odd behavior because kubernetes can't detect its status.
I used the "http-request" image for our main test because this is the only example I could find where it is possible to enter a custom "cmd" and have the service initialize successfully.
> [DIR-1267] Fix e2e Service tests on v2 API

- pkg/refactor/gateway/plugins/auth/gitlab-event.go
- pkg/refactor/gateway/plugins/auth/gitlab-event_test.go
- tests/gateway/gitlab_auth.test.js
Added plugin to authenticate Gitlab webhooks via `X-Gitlab-Token` header.
> [DIR-1253] Added Gitlab webhook plugin

- ui/src/pages/namespace/Instances/Detail/Main/InputOutput/Input.tsx
- ui/src/pages/namespace/Instances/Detail/Main/InputOutput/Output.tsx
Fix console error in Input/Output panel on the instances page
The error was caused by this component composition:
```JSX
<TabsContent value={tabs[0]} className="flex grow" asChild> 
<Input />
</TabsContent>
<TabsContent value={tabs[1]} className="flex grow" asChild>
<Output instanceIsFinished={instanceIsFinished} />
</TabsContent>
```
When a tab component is passed, an `asChild` property, it expects the child component to expose a ref for hooking into the DOM element. This issue does not have any known impact to the issue.
Please note, that there are currently still some other console errors that are caused by the editor. This will be addressed in a different issue.
> [DIR-722] Fix console error in Input/Output panel on the instances page

- ui/src/pages/namespace/Instances/Detail/Main/Logs/Entry.tsx
- ui/src/pages/namespace/Monitoring/Logs/Entry.tsx
Log entry components should never return an empty segment. This will screw up the virtualizes height calculations and the scrolling breaks. This issue was not found earlier because the backend seems to have changed a bit. If I recall correctly the workflow logs always returned a workflow attribute and now this can also be empty.
https://github.com/direktiv/direktiv/assets/121789579/932957bf-bd88-44ff-acde-3f9cec480600
**Workflow to reproduce**
```
description: I will loop and wait on each loop
states:
- id: prep
type: noop
transform:
x: 100
transition: loop
- id: loop
type: switch
conditions:
- condition: "jq(.x > 0)"
transition: wait
- id: wait
type: delay
duration: PT1S
transition: loop
transform:
x: "jq(.x - 1)"
```
> [DIR-1393] fix log scrolling issue

- ui/e2e/explorer/workflow/run.spec.ts
- ui/src/pages/namespace/Explorer/Workflow/components/RunWorkflow.tsx
Before we had a rarely seen bug, where the input fields were filled, but nevertheless were detected as empty by the form.
We found that the reason for this error is a refetch query when the window gets out of focus and back in focus.
(So if you would set _refetchOnWindowFocus: false_ the bug would be gone too, but we want all pages to have the same settings)
Solution was to update the state of the form input on every input event, so the data can't get lost.
> [DIR-1293] JSON Form Input - Fix for copy and pasting values behavior

- charts/direktiv/templates/flow/flow-deployment.yaml
I found some environment variables in flow deployment are hard-coded. These are configured from the value file.
I changed the envs to get values from values or templates.
- dirkectiv services are generated and working in istio mesh cluster.
> [DIR-1409] fix(chart): remove hard-coded envs

- ui/src/components/NavigationBlocker/index.tsx
- ui/src/design/Editor/index.tsx
- ui/src/pages/namespace/Explorer/Consumer/ConsumerEditor/index.tsx
- ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/index.tsx
- ui/src/pages/namespace/Explorer/Service/ServiceEditor/index.tsx
- ui/src/pages/namespace/Explorer/Workflow/Edit/CodeEditor.tsx
This refactors the navigation blocker, removing the react router dependency from storybook where it causes issues.
Instead, there are now two ways of adding the navigation blocker to a page:
1. Import useNavigationBlocker
2. Where (1) isn't possible because the hook is called conditionally, use the `<NavigationBlocker />` component. It does nothing more than calling useNavigationBlocker, but rendering the component conditionally is a recommended React pattern while calling the hook conditionally is not.
It would be possible to remove (1), put all logic into the component, and use only that whenever needed. I am undecided whether we should do that, or support both ways. What do you think, @stefan-kracht ?
> [DIR-1411] Remove router dependency from storybook

- ui/e2e/explorer/route/index.spec.ts
- ui/e2e/explorer/service/index.spec.ts
- ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/Form/index.tsx
- ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/Form/plugins/Auth/index.tsx
- ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/Form/plugins/Inbound/index.tsx
- ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/Form/plugins/Outbound/index.tsx
- ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/Form/plugins/Target/index.tsx
- ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/index.tsx
- ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/schema/plugins/target/schema.ts
- ui/src/pages/namespace/Explorer/Service/ServiceEditor/Form/Patches/index.tsx
- ui/src/pages/namespace/Explorer/Service/ServiceEditor/Form/index.tsx
- ui/src/pages/namespace/Explorer/Service/ServiceEditor/index.tsx
In Services and Endpoints, the file will now be saved to server when clicking save in a subform (e.g., when adding plugins or service patches).
No changes to editing workflows and consumers, because there are no subforms. 
I don't find it 100% logical that the file is saved without clicking the main "save" button under the editor. There are still situations where you have to click it manually (for example, when adding tags in consumers or envs in services). 
But on the other hand, its unlikely to be harmful.
> [DIR-1412] Save files when clicking save in a subform

- ui/e2e/explorer/workflow/codeEditor.spec.ts
- ui/src/api/errorHandling.ts
Saving a workflow with invalid YAML failed silently because the UI did not render the error received in the api response.
The bug occurred because errors are formatted differently in API v1 and v2 and the v2 format wasn't yet implemented in the UI. For now, I decided to support both error response formats because I wasn't sure to what extent v1 errors are still relevant. I also created DIR-1417 so we'll remember to eventually remove the v1 error response format handling.
> [DIR-1336] correctly display v2 api errors when saving workflows

- pkg/jqer/jqer.go
Should resolve DIR-1422 by marshalling and unmarshalling the argument for the JavaScript engine. There might be a better way... Also, I think this JQ/JS component deserves some unit tests to catch this issue.
> [DIR-1422] Should resolve DIR-1422.

- ui/e2e/utils/events.ts
- ui/e2e/utils/files.ts
- ui/src/api/apiFactory.ts
- ui/src/api/enterprise/groups/mutation/create.ts
- ui/src/api/enterprise/groups/mutation/edit.ts
- ui/src/api/enterprise/policy/mutate/update.ts
- ui/src/api/enterprise/tokens/mutate/create.ts
- ui/src/api/events/mutate/sendEvent.ts
- ui/src/api/files/mutate/createFile.ts
- ui/src/api/files/mutate/patchFile.ts
- ui/src/api/jq/mutate/executeQuery.ts
- ui/src/api/namespaces/mutate/createNamespace.ts
- ui/src/api/registries/mutate/createRegistry.ts
- ui/src/api/secrets/mutate/create.ts
- ui/src/api/secrets/mutate/update.ts
- ui/src/api/tree/mutate/runWorkflow.ts
- ui/src/api/variables/mutate/create.ts
- ui/src/api/variables/mutate/update.ts
The current result of a `apiFactory` will type the payload parameter as `unknown`. It would be nice if we could optionally use a generic to add stronger typing to the payload. I know we had a better payload typing at some point, but it came with the downside of us having to pass at `payload:undefined` and we decided to remove that. 
I figured out a solution that lets us optionally type the payload with a generic, without making the payload a mandatory parameter.
I added types to all payloads already.
I added one TODO comment to `ui/src/api/events/mutate/sendEvent.ts`. It seems that the payload might be wrong in the test, or at least it is different from our app usage (this is a good validation on why strong payload typing is very useful 😃). Since the API will be changed in the next cycle, …
> [DIR-1451] add payload type support to api factory

- .github/workflows/k3s-e2e-tests.yml
- openapi/src/openapi.yaml
- openapi/src/paths/notifications.yaml
- pkg/refactor/api/api.go
- pkg/refactor/api/notifications.go
- tests/notifications/uninitialized_secrets.test.js
Migrates the linting api to the v2 api. Also renames it to notifications, recategorizes the secret issue as a warning, and merges all secret issues into a single notification (all at the request of the UI team).
> [DIR-1447] Migrates the linting api to the v2 api, and renames it to notifications.

- ui/e2e/events/history.spec.ts
- ui/e2e/events/listeners.spec.ts
- ui/e2e/explorer/consumer/index.spec.ts
- ui/e2e/explorer/index.spec.ts
- ui/e2e/explorer/route/index.spec.ts
- ui/e2e/explorer/service/index.spec.ts
- ui/e2e/explorer/workflow/codeEditor.spec.ts
- ui/e2e/explorer/workflow/diagramEditor.spec.ts
- ui/e2e/explorer/workflow/run.spec.ts
- ui/e2e/explorer/workflow/settings.spec.ts
- ui/e2e/gateway/consumers/index.spec.ts
- ui/e2e/gateway/routes/details/index.spec.ts
- ui/e2e/gateway/routes/list/index.spec.ts
- ui/e2e/instances/details/index.spec.ts
- ui/e2e/instances/filter/index.spec.ts
- ui/e2e/instances/list/index.spec.ts
- ui/e2e/jqplayground/index.spec.ts
- ui/e2e/mirror.spec.ts
- ui/e2e/notificationmenu/index.spec.ts
- ui/e2e/onboarding.spec.ts
- ui/e2e/services/details.spec.ts
- ui/e2e/services/list.spec.ts
- ui/e2e/settings/deleteNamespace.spec.ts
- ui/e2e/settings/index.spec.ts
- ui/src/util/router/index.tsx
- ui/src/util/router/pages.tsx
This updates the ui to use a prefix for namespaces, resulting in paths like `localhost/n/${namespace}/settings`
Previously, paths were `localhost/${namespace}/settings/`. This might cause conflicts, e.g. a namespace called "api" would cause errors because `localhost/api` is forwarded to the backend.
> [DIR-1456] Add n segment to ui paths to avoid conflicts with api paths

- ui/src/api/authenticate/index.ts
When the user enters the API key on the login screen, the endpoint that is used to check the password is still `/api/v2/status` (previously `api/version`). 
But this endpoint changed to never require any authentication, which means that submitting the password will always be treated as successful. 
When the password is incorrect, the user sees this
> [DIR-1542] - change endpoint that is used for checkApiKeyAgainstServer

- ui/e2e/jqplayground/index.spec.ts
- ui/src/pages/namespace/JqPlayground/index.tsx
When a user clicks an example in the jq Playground, the jqx and input should be stored in local storage to persists after a page reload
> [DIR-1592] jq Playground: store query and input after clicking an example

- ui/e2e/monitoring/index.spec.ts
- ui/src/api/logs/query/logs.ts
- ui/src/pages/namespace/Monitoring/Logs/Entry.tsx
Logs behave differently in CI than on my local machine, because the logs were configured to be in debug level (`logging: json`). On my local machine, I got a default log entry on the monitoring page that was not shown in CI (and production). We should try to use a local setup that is as close to production as possible, I updated our internal wiki and removed the additional flow configuration:
```yaml
flow:
logging: json
debug: true
```
For that test to pass, I now trigger a workflow to produce a log entry on the monitoring page
There was also another issue that this test uncovered. It is technically possible that we can get a log message twice. Once from the initial log request and a second time directly after that via the stream. This is a rare race condition, but since the CI is doing …
> [DIR-1598] enable monitoring logs test and fix log deduplication 

- ui/e2e/events/listeners.spec.ts
- ui/e2e/instances/details/errorHandling.spec.ts
- ui/e2e/instances/filter/index.spec.ts
- ui/e2e/monitoring/index.spec.ts
- ui/e2e/utils/files.ts
- ui/src/api/__tests__/apiFactory.test.ts
- ui/src/api/authenticate/index.ts
- ui/src/api/errorHandling.ts
- ui/src/api/useInfiniteQueryWithPermissions.ts
- ui/src/api/useMutationWithPermissions.ts
- ui/src/api/useQueryWithPermissions.ts
- ui/src/assets/locales/en/translation.json
- ui/src/components/ApiError/index.tsx
- ui/src/pages/namespace/Explorer/index.tsx
- ui/src/pages/namespace/Instances/Detail/Main/Logs/index.tsx
- ui/src/pages/namespace/Layout.tsx
- ui/src/pages/namespace/Monitoring/Logs/index.tsx
- ui/src/util/router/ErrorPage.tsx
Previously, the ui just didn't render any logs when fetching logs failed, e.g. with a 500 server error. With this fix, an error message is rendered when a request returns an error.
Implementation:
* This will display error messages when an error response is received during the non-streaming request. I don't know if an error via streaming would end up being returned by useLogs() in the same way and according to Alexander, the streaming API currently will not return errors (instead, it will just terminate the connection when something fails). I have created DIR-1615 to look at this in more detail.
* I created a component ApiError that should be reusable on every page where we want to pull the `error` prop from a useQuery hook and display an error, so we don't need to implement typesafe …
> [DIR-1608] Display error message on errors when fetching logs

- ui/e2e/explorer/index.spec.ts
We had this test working locally but failing sometimes in CI: 'it is possible to filter the file list by name'
I added 'await' for some checks, where the filter to display a number of elements was used.
That helped heal the error in local headless mode.
But unfortunately this test is still failing on the third retry in CI, so I think it should remain deactivated for now, until we can investigate it thoroughly.
> [DIR-1693] Bug fix for e2e test

- ui/e2e/instances/list/index.spec.ts
- ui/src/assets/locales/en/translation.json
- ui/src/pages/namespace/Instances/List/Row.tsx
- ui/src/pages/namespace/Monitoring/Instances/Row.tsx
Clicking on an instance in the list now always navigates to the instance. The instance's workflow can still be opened from the instance detail view. The direct link to the workflow was removed from the instance list because it confused users intending to navigate to the instance.
> [DIR-1698] Link only to instance from instances list

- ui/src/pages/namespace/Explorer/Tree/components/modals/FileViewer.tsx
Previewing files could destroy the overlay if the path was very long. I fixed this by only showing the filename and not the path. There is still a possibility that this problem could occur if the filename is very long, but I went for an easy and quick fix for now. Extremely long filenames will also need some more love in other parts of the app. 
Before
After
---
It is not possible to have previewable files in the file tree without a git repository. To easily test the bug locally locally, I made this change to make all workflow files previewable.
**src/api/files/utils.ts**
```
export const isPreviewable = (type: BaseFileSchemaType["type"]) =>
type === "file" || type === "workflow";
```
> [DIR-1726] make preview overlay work with long path names

- ui/e2e/explorer/workflow/variables.spec.ts
- ui/src/api/variables/mutate/delete.ts
- ui/src/assets/locales/en/translation.json
- ui/src/pages/namespace/Explorer/Workflow/Settings/Variables/index.tsx
- ui/src/pages/namespace/Settings/Variables/Delete.tsx
- ui/src/pages/namespace/Settings/Variables/index.tsx
- ui/src/pages/namespace/Settings/components/ItemRow.tsx
- Added multi-select functionality for variables using checkboxes
- Implemented "Select All" feature with dropdown indicator
- Enhanced delete dialog to handle single/multiple/all item scenarios with appropriate messaging
- Added a dedicated delete button in the toolbar for selected items
- There is a problem with not implementing the multiple delete functionality in both Settings and Explorer since, the same ItemRow, Delete components and delete.ts mutation file is used. So the old delete btn is not working at the moment in explorer view, but I couldn't remove it since it is used in the Settings section. 
This will be cleaner after we implement it in both places. :)
https://github.com/user-attachments/assets/2a98d761-d6f0-41dd-98d7-5adf9cbb1464
> [DIR-1807] - Add ability to select and delete multiple workflow variables

- ui/src/assets/locales/en/translation.json
- ui/src/components/NamespaceEdit/index.tsx
- ui/src/components/NamespaceSelectorList/index.tsx
- Added tooltip targeting namespace named 'system' to inform the user about the properties that this namespace contains. 
- Added tooltip to name field when creating a namespace, to inform the user about that they can use the name 'system' and what it means.
https://github.com/user-attachments/assets/9624a1d3-6060-44e5-9562-01a952bfb180
> [DIR-1496] - UI support for system namespace

- ui/e2e/events/history.spec.ts
- ui/src/components/Pagination/index.tsx
- ui/src/components/PaginationProvider/index.tsx
- ui/src/pages/namespace/Events/History/EventsList.tsx
- ui/src/pages/namespace/Events/Listeners/index.tsx
- ui/src/pages/namespace/Explorer/Workflow/Settings/Variables/index.tsx
- ui/src/pages/namespace/Instances/List/index.tsx
- ui/src/pages/namespace/Mirror/Detail/index.tsx
- ui/src/pages/namespace/Settings/Registries/index.tsx
- ui/src/pages/namespace/Settings/Secrets/index.tsx
- ui/src/pages/namespace/Settings/Variables/index.tsx
This makes the pagination and pagesize (number of items in the list on one page) always visible, also if the list is empty.
> [DIR-1897] Made pagination always visible and show page number 1 for an empty list

- ui/e2e/gateway/info/index.spec.ts
- ui/src/api/gateway/index.ts
- ui/src/api/gateway/query/getInfo.ts
- ui/src/api/gateway/schema.ts
- ui/src/assets/locales/en/translation.json
- ui/src/components/Breadcrumb/Gateway/GatewayInfo.tsx
- ui/src/components/Breadcrumb/Gateway/Routes.tsx
- ui/src/components/Breadcrumb/Gateway/index.tsx
- ui/src/pages/namespace/Gateway/Info/index.tsx
- ui/src/pages/namespace/Gateway/index.tsx
- ui/src/util/router/pages.tsx
Added:
- Info tab to Gateway section
- with a table showing the basic info; Title, Version, Description, and also included File
- Breadcrumbs
- Yaml view
> [DIR-1901] - Add info tab to gateview view

- ui/e2e/gateway/routes/utils.ts
This adds back more specific error handling to gateway e2e tests. Previously, tests were allowed to fail silently on a 500 server error because they sometimes occurred during tests when a resource didn't exist. Now, the backend has implemented 404 errors, and the tests have been updated to throw errors on a 500 error so we don't miss those unexpected ones.
Note: 
Locally, this test fails: "the logs panel can be resized, it displays a log message from the workflow yaml, one initial and one final log entry" -- but this is unrelated to my changes (also happens on main), and does not happen in the CI, so I'm ignoring it for now.
> [DIR-1507] only quit silently on 404 errors in e2e test

- ui/e2e/gateway/consumers/index.spec.ts
- ui/e2e/gateway/routes/details/index.spec.ts
- ui/e2e/gateway/routes/list/index.spec.ts
- ui/src/components/Breadcrumb/Gateway/Routes.tsx
- ui/src/components/Breadcrumb/Gateway/index.tsx
- ui/src/components/Breadcrumb/index.tsx
- ui/src/pages/namespace/Explorer/Endpoint/index.tsx
- ui/src/pages/namespace/Gateway/Routes/Detail/Header.tsx
- ui/src/pages/namespace/Gateway/Routes/Detail/index.tsx
- ui/src/pages/namespace/Gateway/Routes/Table/Row.tsx
- ui/src/pages/namespace/Gateway/index.tsx
- ui/src/routeTree.gen.ts
- ui/src/routes/n/$namespace/gateway/index.tsx
- ui/src/routes/n/$namespace/gateway/route.tsx
- ui/src/routes/n/$namespace/gateway/routes/$.tsx
In the tanstack router migration, I missed the tabs that allow navigating between consumers and routes under the gateway route. This fixes that and also adds e2e tests for navigating to the consumers page and back.
> [DIR-1941] Restore gateway tabs

- ui/e2e/mirror.spec.ts
- ui/src/pages/namespace/Mirror/Detail/Sync/SyncDetail.tsx
- ui/src/pages/namespace/Mirror/Detail/Sync/index.tsx
This fixes passing the sync id parameter to the components that need it to show the logs, and adds a test to ensure the logs can be viewed.
This was an oversight in the migration to tanstack router.
Main is currently broken, so this does not pass all checks either but I think we should still go ahead and merge as this doesn't add new issues.
> [DIR-1948] Fix sync param for displaying sync logs

- ui/src/components/Navigation/index.tsx
- ui/src/routeTree.gen.ts
- ui/src/routes/n/$namespace/events/index.tsx
- ui/src/routes/n/$namespace/gateway/index.tsx
When visiting sub sections of Events and Gateway through the tabs, main navigation lost the active state. This PR fixes that with the help of two index.tsx routing files.
https://github.com/user-attachments/assets/b41cc8e1-58a8-43f2-be14-ac834c472862
> [DIR-1970] - Fix navigation active state bug

- pkg/core/app.go
- pkg/flow/grpc-flow.go
- pkg/flow/server.go
- pkg/instancestore/instancestoresql/sql.go
- pkg/mirror/manager.go
This PR addresses two things:
1. It lets the backend auto-cleanup bugged instances. I don't even know if we still create bugged instances, but I've had to support some old versions of Direktiv where we manually had to interact with the database to remove broken instances that were weeks old. 
2. It lets the user configure their garbage collection to be more aggressive. I have seen Direktiv used in environments where it ingests dozens of gigabytes of data into workflows every day. And they were trying to run the entire cluster on a 100GiB disk. With these changes, users can make tweak the garbage collector to be more aggressive if they want. They can purge their old instances after 3 hours if they want. It's up to them. 
This is tangentially related to DIR-1871.
> Makes garbage collection configurable.

- ui/e2e/explorer/route/index.spec.ts
- ui/e2e/instances/details/logs.spec.ts
- ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/Form/index.tsx
- ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/schema/index.ts
Route logs did not work previously when the "path" in the route definition lacked a leading slash:
* `foo` or `foo/bar` -> no logs found
* `/foo` or `/foo/bar` -> logs found
The old API did not require a leading slash, the new API does.
To ensure our route definition files will always have paths with leading slashes, 2 changes have been implemented:
* a `z.preprocess()` that will update files loaded that do not yet have a leading slash for path,
* a setValue() in the Input component for the path that makes sure a `/` is always added when editing it (without this, it would get added through the schema before saving, but react would not be aware of the updated value and not update the DOM to reflect it).
These …
> [DIR-2016] Fix fetching logs for routes (enforce leading slash in route path)

- ui/e2e/explorer/route/index.spec.ts
During the OpenAPI update, there was one E2E test that was tricky to adapt to the new routes file format. I postponed fixing the test to move forward with the ticket. This PR will now reenable the test and fix all issues so that is turns green again.
The main issue that I did not find back then was a typo: `trues` instead of `true`. After finding that, I could move on with fixing everything below that one by one.
> [DIR-1958] make route e2e test work again

- .github/workflows/build.yml
- cmd/main.go
- go.mod
- go.sum
- ui/src/assets/locales/en/translation.json
- ui/src/pages/namespace/Explorer/Page/poc/BlockEditor/Text.tsx
- ui/src/pages/namespace/Explorer/Page/poc/BlockEditor/index.tsx
- ui/src/pages/namespace/Explorer/Page/poc/BlockEditor/utils.ts
- ui/src/pages/namespace/Explorer/Page/poc/PageCompiler/Block/Card.tsx
- ui/src/pages/namespace/Explorer/Page/poc/PageCompiler/Block/Columns.tsx
- ui/src/pages/namespace/Explorer/Page/poc/PageCompiler/Block/Dialog.tsx
- ui/src/pages/namespace/Explorer/Page/poc/PageCompiler/Block/Loop.tsx
- ui/src/pages/namespace/Explorer/Page/poc/PageCompiler/Block/QueryProvider.tsx
- ui/src/pages/namespace/Explorer/Page/poc/PageCompiler/Block/index.tsx
- ui/src/pages/namespace/Explorer/Page/poc/PageCompiler/Block/utils/BlockWrapper.tsx
- ui/src/pages/namespace/Explorer/Page/poc/PageCompiler/context/pageCompilerContext.tsx
- ui/src/pages/namespace/Explorer/Page/poc/PageCompiler/context/utils.ts
- ui/src/pages/namespace/Explorer/Page/poc/PageEditor.tsx
- ui/src/pages/namespace/Explorer/Page/poc/schema/__tests__/examples/complex.ts
- ui/src/pages/namespace/Explorer/Page/poc/schema/__tests__/examples/simple.ts
- ui/src/pages/namespace/Explorer/Page/poc/schema/blocks/columns.ts
- ui/src/pages/namespace/Explorer/Page/poc/schema/blocks/index.ts
This adds the following hooks to update pages:
* useBlock() (was already there)
* useSetPage() (to update the page in the context)
* useUpdateBlock() (to update a block at a specified path)
* useAddBlock() (to insert a block at a specified path)
Furthermore, a demo editor block for text blocks was added, using these hooks to update the page.
The hooks targeting specific blocks should be used over useSetPage() whenever possible.
The hooks are defined in 
src/pages/namespace/Explorer/Page/poc/PageCompiler/context/pageCompilerContext.tsx
and relying on methods defined in a utils folder.
We should add unit tests for the hooks and/or utils, for which I have created DIR-2034.
> [DIR-2033] Add methods to update blocks and pages

- ui/src/pages/namespace/Explorer/Page/poc/PageCompiler/Block/utils/BlockList.tsx
- ui/src/pages/namespace/Explorer/Page/poc/PageCompiler/context/__tests__/utils.test.ts
- ui/src/pages/namespace/Explorer/Page/poc/PageCompiler/context/utils/index.ts
- ui/src/pages/namespace/Explorer/Page/poc/PageCompiler/context/utils/useBlockTypes.tsx
This fixes an error in detecting block types in the ancestors of a block when rendering the type selector menu for adding a new block. There are two sides to this:
* First, when adding a block in an empty list, we previously didn't begin parsing ancestors at the path of the new block, but at the parent.
* Second, I have changed findInPath to findAncestor. It makes more sense to always start at the parent path because the block at the current path should already be known. I have updated the tests accordingly.
The depth param also makes more sense now: depth 0 does not run any iterations. That's why I added a guard that throws an Error when depth is smaller than 1.
When path is [], no parents exist, but it fails silently, as this can happen naturally at the root of the path.
> [TDI-57] Allow cards below other cards

- ui/src/pages/namespace/Explorer/Page/poc/DndContextProvider/index.tsx
- ui/src/pages/namespace/Explorer/Page/poc/PageCompiler/context/pageCompilerContext.tsx
This wraps the moveBlockWithinPage function in a method inside the usePageEditor hook.
> Add moveBlock method to usePageEditor

- ui/src/design/DragAndDrop/Draggable.tsx
- ui/src/design/DragAndDrop/index.stories.tsx
- ui/src/pages/namespace/Explorer/Page/poc/BlockEditor/components/EditorPanel.tsx
- ui/src/pages/namespace/Explorer/Page/poc/PageCompiler/Block/utils/BlockWrapper.tsx
- ui/src/pages/namespace/Explorer/Page/poc/PageCompiler/context/__tests__/utils.test.ts
- ui/src/pages/namespace/Explorer/Page/poc/PageCompiler/context/utils/index.ts
In this PR I changed the dropzone to be placed after every block instead of before, because with that the "editor" view is more aligned with the layout that is shown in the "live" view.
Additionally I renamed a variable, where the spelling was different than for the others.
I also fixed a visual issue with the z-index of the blocks.
> [TDI-90] Show dropzone after every block instead of before

- ui/src/design/DragAndDrop/Dropzone.tsx
- ui/src/pages/namespace/Explorer/Page/poc/BlockEditor/EditorPanelProvider.tsx
- ui/src/pages/namespace/Explorer/Page/poc/BlockEditor/components/EditorPanel.tsx
- ui/src/pages/namespace/Explorer/Page/poc/PageCompiler/Block/Dialog.tsx
- ui/src/pages/namespace/Explorer/Page/poc/PageCompiler/Block/utils/BlockWrapper.tsx
- ui/src/pages/namespace/Explorer/Page/poc/PageCompiler/context/__tests__/utils.test.ts
- ui/src/pages/namespace/Explorer/Page/poc/PageCompiler/context/utils/index.ts
This tweaks how dropzones are disabled.
* Previously, they were only hidden by the isVisible prop, but you could still drop something and the action would be triggered.
* Now, the "enable" function prop will prevent them from rendering the drop zone hint as well as set them to "disabled" via the useDroppable() API.
* The editor panel context now has a "dialog" property. If a dialog is open, this is set to the path of the dialog block.
* With a dialog open, only drop zones inside the dialog block's scope are enabled.
Follow-up: TDI-92 "Dropzones should know what block types are allowed to be dropped". This will extend this logic further (but TDI-77 with the single config layer should be merged first).
> [TDI-87] Limit enabled dropzones to dialog if dialog is open

- ui/src/assets/locales/en/translation.json
- ui/src/design/DragAndDrop/Draggable.tsx
- ui/src/design/LocalDialog/container.tsx
- ui/src/design/LocalDialog/index.tsx
- ui/src/pages/namespace/Explorer/Page/poc/BlockEditor/EditorPanelProvider.tsx
- ui/src/pages/namespace/Explorer/Page/poc/BlockEditor/components/Delete.tsx
- ui/src/pages/namespace/Explorer/Page/poc/BlockEditor/components/EditorPanel.tsx
- ui/src/pages/namespace/Explorer/Page/poc/PageCompiler/context/pageCompilerContext.tsx
- ui/src/pages/namespace/Explorer/Page/poc/PageEditor/ButtonBar.tsx
- ui/src/pages/namespace/Explorer/Page/poc/PageEditor/EditorModeSwitcher.tsx
- ui/src/pages/namespace/Explorer/Page/poc/PageEditor/index.tsx
This PR overhauls the bottom toolbar. I went with a very simple approach and decided to do a button bar with three buttons to view code, edit and preview the page similar to the workflow editor.
I decided not to store the selected button state in localstorage as we normally do for these kinds of view settings. I am happy to change that if anyone has a strong opinion on that.
- There is not an explicit "copy code button" but I think this does not need an extra button when you see the code. 
- I changed the editor to be read-only
- the height of the main Card will adjust to the window height, and the right panel will overflow with a scrollbar if needed.
- the left panel currently does not overflow if the content is too big to fit in. This must be improved in a future version (as a form …
> [TDI-80] overhaul page editor bottom toolbar

- ui/src/components/StopPropagation/index.tsx
- ui/src/pages/namespace/Explorer/Page/poc/PageCompiler/Block/formPrimitives/FormCheckbox.tsx
- ui/src/pages/namespace/Explorer/Page/poc/PageCompiler/Block/formPrimitives/FormDateInput/DatePicker.tsx
- ui/src/pages/namespace/Explorer/Page/poc/PageCompiler/Block/formPrimitives/FormNumberInput.tsx
- ui/src/pages/namespace/Explorer/Page/poc/PageCompiler/Block/formPrimitives/FormSelect.tsx
- ui/src/pages/namespace/Explorer/Page/poc/PageCompiler/Block/formPrimitives/FormStringInput.tsx
- ui/src/pages/namespace/Explorer/Page/poc/PageCompiler/Block/formPrimitives/FormTextarea.tsx
- ui/src/pages/namespace/Explorer/Page/poc/PageCompiler/Block/formPrimitives/utils/FieldSet.tsx
This fixes the onClick behavior of form elements in the page editor.
* I have created a <StopPropagation> helper component that will do just that, and wrapped form elements in it (easier than adding the onClick prop manually, and also easy to read).
* Clicking on the label should still always trigger the side panel (there is no other way to reliably focus/unfocus when no description exists for a form element). 
* For the checkbox, I have even added logic that overrides the label's default behavior (toggling the checkbox) when in edit mode.
* For the date picker, I also have added code that will close it when a date has been selected (previously it stayed open).
> [TDI-106] Fix form element side panel interactions

- ui/src/pages/namespace/Explorer/Page/poc/BlockEditor/Form/Checkbox.tsx
- ui/src/pages/namespace/Explorer/Page/poc/BlockEditor/Form/NumberInput.tsx
- ui/src/pages/namespace/Explorer/Page/poc/BlockEditor/Loop.tsx
- ui/src/pages/namespace/Explorer/Page/poc/BlockEditor/QueryProvider/QueryForm.tsx
- ui/src/pages/namespace/Explorer/Page/poc/BlockEditor/Table/ColumnForm.tsx
- ui/src/pages/namespace/Explorer/Page/poc/BlockEditor/Table/index.tsx
- ui/src/pages/namespace/Explorer/Page/poc/BlockEditor/components/FormElements/ExtendedKeyValueInput/VariableValueInput.tsx
- ui/src/pages/namespace/Explorer/Page/poc/BlockEditor/components/SmartInput/index.tsx
- ui/src/pages/namespace/Explorer/Page/poc/BlockEditor/components/TreePicker/index.tsx
- ui/src/pages/namespace/Explorer/Page/poc/BlockEditor/components/VariableInput/index.tsx
- ui/src/pages/namespace/Explorer/Page/poc/BlockEditor/components/VariablePicker/index.tsx
This adds variable pickers to individual fields where it was still missing (TDI-129), and also implements a `<VariableInput />` component for fields that contain only a variable (not a template string).
The VariableInput is a minimal "MVP" implementation that could be realized quite quickly with the existing TreePicker. There is room for a few possible improvements, including better UI or hints to help the user understand that they are replacing the input value when they pick a variable, or editing existing variable pointers. However, in terms of covering the basics, I am already quite happy with this.
@stefan-kracht I am marking this as "ready for review", but as discussed, you're welcome to improve it further while I am away.
> [TDI-129][TDI-130] Add variable picker to pointers, table, query-provider (url)

- cmd/cli/filesystem_helper.go
- internal/api/instances.go
- tests/engine/create_run_workflow.test.js
- ui/src/pages/namespace/Instances/Detail/Main/InputOutput/Input.tsx
- ui/src/pages/namespace/Instances/Detail/Main/InputOutput/Output.tsx
- ui/src/pages/namespace/Instances/List/Row.tsx
This change removes the base64 encoding from instance's **errorMessage**, **input** and **output** fields. Fields **input** and **output** are json values which are safe. Field **errorMessage** is a human readable text.
> [TDI-149] remove base64 encoding for instance object fields
